"use client";
import { useState } from "react";
import StudioHeader from "../../components/StudioHeader";
import { useRadioSchedule } from "../../hooks/useRadioSchedule";
import type { RadioProgram, RadioProgramInput, RadioProgramStatus, RadioScheduleType } from "../../lib/radioSchedule/types";

const days = [[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"],[7,"Sun"]] as const;
const empty = (): RadioProgramInput => ({ title:"", description:null, host_id:null, host_name:null, schedule_type:"one_time", starts_at:null, ends_at:null, days_of_week:[], start_time:null, end_time:null, timezone:"America/Los_Angeles", effective_from:null, effective_until:null, is_published:false, status:"draft", display_order:100 });
function dateInput(value: string | null) { if (!value) return ""; const d = new Date(value); const offset = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - offset).toISOString().slice(0,16); }

export default function RadioScheduleAdminPage() {
  const schedule = useRadioSchedule("admin");
  const [form, setForm] = useState<RadioProgramInput>(empty());
  const [editing, setEditing] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const set = <K extends keyof RadioProgramInput>(key: K, value: RadioProgramInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  function edit(program: RadioProgram) { setEditing(program.id); setForm({ title:program.title, description:program.description, host_id:program.host_id, host_name:program.host_name, schedule_type:program.schedule_type, starts_at:program.starts_at, ends_at:program.ends_at, days_of_week:program.days_of_week || [], start_time:program.start_time, end_time:program.end_time, timezone:program.timezone, effective_from:program.effective_from, effective_until:program.effective_until, is_published:program.status === "published", status:program.status, display_order:program.display_order }); window.scrollTo({top:0,behavior:"smooth"}); }
  async function save() { setNotice(""); try { if (editing) await schedule.update(editing, form); else await schedule.create(form); setForm(empty()); setEditing(null); setNotice("Radio program saved."); } catch {} }
  async function remove(id: string) { if (!window.confirm("Delete this radio program?")) return; try { await schedule.remove(id); setNotice("Radio program deleted."); } catch {} }
  return <main className="min-h-screen bg-slate-950 text-white"><StudioHeader/><div className="mx-auto max-w-7xl px-5 py-10"><p className="font-black uppercase tracking-wide text-pink-300">Radio Operations</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Radio Schedule</h1><p className="mt-2 text-slate-300">Publish dated shows or a recurring daily and weekly schedule.</p>
    {(schedule.error || notice) && <div className={`mt-6 rounded-2xl p-4 font-bold ${schedule.error ? "bg-red-100 text-red-900" : "bg-green-100 text-green-900"}`}>{schedule.error || notice}</div>}
    <section className="mt-8 rounded-3xl bg-white p-6 text-slate-950"><h2 className="text-2xl font-black">{editing ? "Edit Program" : "Add Program"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2">
      <label className="font-bold">Program / Segment Name<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.title} onChange={(e)=>set("title",e.target.value)}/></label>
      <label className="font-bold">Host Name<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.host_name || ""} onChange={(e)=>set("host_name",e.target.value)}/></label>
      <label className="font-bold md:col-span-2">Description<textarea className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal" value={form.description || ""} onChange={(e)=>set("description",e.target.value)}/></label>
      <label className="font-bold">Schedule Type<select className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.schedule_type} onChange={(e)=>set("schedule_type",e.target.value as RadioScheduleType)}><option value="one_time">One-time dated show</option><option value="daily">Every day</option><option value="weekly">Selected weekdays</option></select></label>
      <label className="font-bold">Workflow Status<select className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.status} onChange={(e)=>set("status",e.target.value as RadioProgramStatus)}><option value="draft">Draft — still being prepared</option><option value="published">Published — visible publicly</option><option value="on_hold">On Hold — temporarily hidden</option><option value="archived">Archived — retired</option></select></label>
      {form.schedule_type === "one_time" ? <><label className="font-bold">Starts<input type="datetime-local" className="mt-1 w-full rounded-xl border p-3 font-normal" value={dateInput(form.starts_at)} onChange={(e)=>set("starts_at",e.target.value ? new Date(e.target.value).toISOString() : null)}/></label><label className="font-bold">Ends<input type="datetime-local" className="mt-1 w-full rounded-xl border p-3 font-normal" value={dateInput(form.ends_at)} onChange={(e)=>set("ends_at",e.target.value ? new Date(e.target.value).toISOString() : null)}/></label></> : <><label className="font-bold">Start Time<input type="time" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.start_time || ""} onChange={(e)=>set("start_time",e.target.value)}/></label><label className="font-bold">End Time<input type="time" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.end_time || ""} onChange={(e)=>set("end_time",e.target.value)}/></label>{form.schedule_type === "weekly" && <div className="md:col-span-2"><p className="font-bold">Days</p><div className="mt-2 flex flex-wrap gap-2">{days.map(([number,label])=><label key={number} className="rounded-xl border px-3 py-2 font-bold"><input type="checkbox" className="mr-2" checked={form.days_of_week.includes(number)} onChange={(e)=>set("days_of_week",e.target.checked ? [...form.days_of_week,number] : form.days_of_week.filter((day)=>day!==number))}/>{label}</label>)}</div></div>}<label className="font-bold">Effective From (optional)<input type="date" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.effective_from || ""} onChange={(e)=>set("effective_from",e.target.value || null)}/></label><label className="font-bold">Effective Until (optional)<input type="date" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.effective_until || ""} onChange={(e)=>set("effective_until",e.target.value || null)}/></label></>}
    </div><div className="mt-6 flex gap-3"><button disabled={schedule.saving} onClick={save} className="rounded-xl bg-pink-600 px-5 py-3 font-black text-white disabled:opacity-50">{schedule.saving ? "Saving..." : "Save Program"}</button>{editing && <button onClick={()=>{setEditing(null);setForm(empty());}} className="rounded-xl border px-5 py-3 font-black">Cancel</button>}</div></section>
    <section className="mt-8 rounded-3xl bg-white p-6 text-slate-950"><h2 className="text-2xl font-black">All Programs</h2>{schedule.loading ? <p className="mt-4 text-slate-500">Loading...</p> : <div className="mt-5 grid gap-4 md:grid-cols-2">{schedule.programs.map((program)=><article key={program.id} className="rounded-2xl border p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase text-pink-600">{program.schedule_type.replace("_"," ")} · {program.status.replace("_"," ")}</p><h3 className="mt-1 text-xl font-black">{program.title}</h3><p className="text-slate-600">{program.host?.name || program.host_name || "No host assigned"}</p></div><div className="flex h-fit gap-2"><button onClick={()=>edit(program)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">Edit</button><button onClick={()=>remove(program.id)} className="rounded-lg border border-red-300 px-3 py-2 text-sm font-bold text-red-700">Delete</button></div></div></article>)}{!schedule.programs.length && <p className="text-slate-500">No radio programs added yet.</p>}</div>}</section>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-black">App Developer API</h2><p className="mt-2 text-slate-300">Public, read-only JSON endpoint:</p><code className="mt-3 block overflow-x-auto rounded-xl bg-black/30 p-4 text-pink-200">https://seattledesitv.com/api/radio/schedule</code></section>
  </div></main>;
}
