-- SDTV Restore v2: primary keys
-- Run after ../schema/tables.sql.
-- Idempotent: skips tables that already have a primary key.

do $$
begin
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='admins' and constraint_type='PRIMARY KEY') then alter table public.admins add constraint admins_pkey primary key (user_id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='community_groups' and constraint_type='PRIMARY KEY') then alter table public.community_groups add constraint community_groups_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='community_organizations' and constraint_type='PRIMARY KEY') then alter table public.community_organizations add constraint community_organizations_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='contact_requests' and constraint_type='PRIMARY KEY') then alter table public.contact_requests add constraint contact_requests_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='crew_availability' and constraint_type='PRIMARY KEY') then alter table public.crew_availability add constraint crew_availability_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_coverage_sources' and constraint_type='PRIMARY KEY') then alter table public.event_coverage_sources add constraint event_coverage_sources_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_crew_assignments' and constraint_type='PRIMARY KEY') then alter table public.event_crew_assignments add constraint event_crew_assignments_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_crew_media_submissions' and constraint_type='PRIMARY KEY') then alter table public.event_crew_media_submissions add constraint event_crew_media_submissions_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_deliverables' and constraint_type='PRIMARY KEY') then alter table public.event_deliverables add constraint event_deliverables_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_influencer_intents' and constraint_type='PRIMARY KEY') then alter table public.event_influencer_intents add constraint event_influencer_intents_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_video_notifications' and constraint_type='PRIMARY KEY') then alter table public.event_video_notifications add constraint event_video_notifications_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_video_revisions' and constraint_type='PRIMARY KEY') then alter table public.event_video_revisions add constraint event_video_revisions_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='event_video_workflows' and constraint_type='PRIMARY KEY') then alter table public.event_video_workflows add constraint event_video_workflows_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='events' and constraint_type='PRIMARY KEY') then alter table public.events add constraint events_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='featured_social_content' and constraint_type='PRIMARY KEY') then alter table public.featured_social_content add constraint featured_social_content_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='festival_hero_assets' and constraint_type='PRIMARY KEY') then alter table public.festival_hero_assets add constraint festival_hero_assets_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='hero_analytics' and constraint_type='PRIMARY KEY') then alter table public.hero_analytics add constraint hero_analytics_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='homepage_hero_banners' and constraint_type='PRIMARY KEY') then alter table public.homepage_hero_banners add constraint homepage_hero_banners_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='homepage_settings' and constraint_type='PRIMARY KEY') then alter table public.homepage_settings add constraint homepage_settings_pkey primary key (section_key); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='homepage_sponsors' and constraint_type='PRIMARY KEY') then alter table public.homepage_sponsors add constraint homepage_sponsors_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='homepage_testimonials' and constraint_type='PRIMARY KEY') then alter table public.homepage_testimonials add constraint homepage_testimonials_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='influencer_profiles' and constraint_type='PRIMARY KEY') then alter table public.influencer_profiles add constraint influencer_profiles_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='local_businesses' and constraint_type='PRIMARY KEY') then alter table public.local_businesses add constraint local_businesses_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='newsletter_campaigns' and constraint_type='PRIMARY KEY') then alter table public.newsletter_campaigns add constraint newsletter_campaigns_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='newsletter_settings' and constraint_type='PRIMARY KEY') then alter table public.newsletter_settings add constraint newsletter_settings_pkey primary key (section_key); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='newsletter_subscribers' and constraint_type='PRIMARY KEY') then alter table public.newsletter_subscribers add constraint newsletter_subscribers_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='notifications' and constraint_type='PRIMARY KEY') then alter table public.notifications add constraint notifications_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='public_content_requests' and constraint_type='PRIMARY KEY') then alter table public.public_content_requests add constraint public_content_requests_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='public_visibility_controls' and constraint_type='PRIMARY KEY') then alter table public.public_visibility_controls add constraint public_visibility_controls_pkey primary key (email); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='radio_team_members' and constraint_type='PRIMARY KEY') then alter table public.radio_team_members add constraint radio_team_members_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='social_media_stats' and constraint_type='PRIMARY KEY') then alter table public.social_media_stats add constraint social_media_stats_pkey primary key (platform); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='sponsors' and constraint_type='PRIMARY KEY') then alter table public.sponsors add constraint sponsors_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='team_members' and constraint_type='PRIMARY KEY') then alter table public.team_members add constraint team_members_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='user_profiles' and constraint_type='PRIMARY KEY') then alter table public.user_profiles add constraint user_profiles_pkey primary key (user_id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='user_role_requests' and constraint_type='PRIMARY KEY') then alter table public.user_role_requests add constraint user_role_requests_pkey primary key (id); end if;
  if not exists (select 1 from information_schema.table_constraints where table_schema='public' and table_name='volunteer_onboarding_submissions' and constraint_type='PRIMARY KEY') then alter table public.volunteer_onboarding_submissions add constraint volunteer_onboarding_submissions_pkey primary key (id); end if;
end $$;
