"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import StudioHeader from "../../components/StudioHeader";
import { getSupabaseBrowserClient } from "../../lib/supabaseBrowser";
import { isAdminRole, resolveUserRole } from "../../lib/roles";
import { loadAllListingRequests, reviewListingRequest } from "../../lib/listingManagement/services/listingManagementService";
import type { ListingManagementRequest, ListingRequestStatus } from "../../lib/listingManagement/types";

const supabase = getSupabaseBrowserClient();
export default function ListingRequestsStudioPage() {
  const [user, setUser] = useState<User | null>(null); const [rows, setRows] = useState<ListingManagementRequest[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [filter, setFilter] = useState("pending"); const [notes, setNotes] = useState<Record<string, string>>({}); const [working, setWorking] = useState("");
  async function load() { setLoading(true); const { data } = await supabase.auth.getUser(); const current = data?.user || null; setUser(current); if (!current || !isAdminRole(await resolveUserRole(supabase, current))) { setMessage("Studio admin access is required."); setLoading(false); return; } try { setRows(await loadAllListingRequests(supabase)); } catch (cause: unknown) { setMessage(cause instanceof Error ? cause.message : "Could not load requests."); } setLoading(false); }
  // Loading the moderation queue is the purpose of this mount effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => filter === "all" ? rows : rows.filter((row) => row.status === filter), [rows, filter]);
  async function review(row: ListingManagementRequest, status: ListingRequestStatus) { if (!user?.id) return; if (status === "approved" && row.request_type === "correction" && !(notes[row.id] || "").trim()) { setMessage("Add a note confirming which correction was applied before approval."); return; } setWorking(row.id); setMessage(""); try { await reviewListingRequest(supabase, row, status, notes[row.id] || "", user.id); await load(); setMessage(status === "approved" ? "Request approved and the corresponding access or removal was applied." : "Request updated."); } catch (cause: unknown) { setMessage(cause instanceof Error ? cause.message : "Could not update the request."); } setWorking(""); }
  return <main className="min-h-screen bg-slate-100 text-slate-950"><StudioHeader /><section className="mx-auto max-w-7xl px-6 py-10"><p className="text-sm font-black uppercase tracking-wide text-pink-600">Community moderation</p><h1 className="mt-2 text-4xl font-black">Listing Requests</h1><p className="mt-2 text-slate-600">Review claims, corrections, and removal requests for events, influencers, and community groups.</p><div className="mt-6 flex flex-wrap gap-2">{["pending", "needs_information", "approved", "rejected", "all"].map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-4 py-2 text-sm font-black ${filter === value ? "bg-pink-600 text-white" : "bg-white"}`}>{value.replace("_", " ")}</button>)}</div>{message && <p className="mt-5 rounded-xl bg-yellow-50 p-4 font-bold text-yellow-900">{message}</p>}{loading ? <p className="mt-6">Loading...</p> : <div className="mt-6 grid gap-4">{visible.map((row) => <article key={row.id} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-pink-600">{row.entity_type.replace("_", " ")} · {row.request_type}</p><h2 className="mt-1 text-2xl font-black">{row.entity_name}</h2><p className="mt-1 text-sm text-slate-500">{row.requester_name} · {row.requester_email}{row.relationship ? ` · ${row.relationship}` : ""}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase">{row.status.replace("_", " ")}</span></div><p className="mt-4 whitespace-pre-line rounded-2xl bg-slate-50 p-4 text-slate-700">{row.details}</p><textarea value={notes[row.id] ?? row.admin_notes ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [row.id]: event.target.value }))} placeholder="Admin notes or information needed..." className="mt-4 min-h-24 w-full rounded-xl border p-3" /><div className="mt-3 flex flex-wrap gap-2"><button disabled={working === row.id} onClick={() => review(row, "approved")} className="rounded-xl bg-green-700 px-4 py-2 font-black text-white">Approve</button><button disabled={working === row.id} onClick={() => review(row, "needs_information")} className="rounded-xl bg-yellow-400 px-4 py-2 font-black">Request information</button><button disabled={working === row.id} onClick={() => review(row, "rejected")} className="rounded-xl bg-red-700 px-4 py-2 font-black text-white">Reject</button></div></article>)}{visible.length === 0 && <p className="rounded-2xl bg-white p-6 text-slate-500">No matching requests.</p>}</div>}</section></main>;
}
