import type { ReactNode } from "react";

export default function HomeV2Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        main > section:has(a[href="/recognition"]) { isolation:isolate; overflow:hidden!important; border:0!important; min-height:225px!important; background:radial-gradient(circle at 18% 48%,rgba(255,205,68,.24),transparent 18rem),radial-gradient(circle at 82% 26%,rgba(236,72,153,.22),transparent 19rem),linear-gradient(105deg,#090306 0%,#1a0612 36%,#2b0718 62%,#10030b 100%)!important; }
        main > section:has(a[href="/recognition"]) > div:first-child, main > section:has(a[href="/recognition"]) > div:last-child { color:#fff!important; opacity:1; position:relative; z-index:5; height:34px!important; }
        main > section:has(a[href="/recognition"])::before { content:""; position:absolute; inset:0; z-index:0; pointer-events:none; background:radial-gradient(circle,rgba(250,204,21,.62) 1px,transparent 1.7px),radial-gradient(circle,rgba(255,255,255,.16) 1px,transparent 1.6px); background-size:34px 34px,72px 72px; background-position:0 0,18px 10px; opacity:.65; }
        main > section:has(a[href="/recognition"])::after { content:""; position:absolute; inset:0; z-index:1; pointer-events:none; background:radial-gradient(ellipse at 2% 18%,rgba(255,216,91,.62),transparent 24%),radial-gradient(ellipse at 100% 55%,rgba(250,204,21,.42),transparent 30%),linear-gradient(170deg,transparent 0 14%,rgba(255,225,101,.76) 17.5%,rgba(250,204,21,.30) 21%,transparent 28%),linear-gradient(358deg,transparent 0 44%,rgba(255,231,123,.72) 49%,rgba(250,204,21,.22) 53%,transparent 62%),linear-gradient(173deg,transparent 0 79%,rgba(255,224,94,.70) 83%,rgba(250,204,21,.13) 87%,transparent 91%); filter:drop-shadow(0 0 22px rgba(250,204,21,.28)); opacity:1; }
        main > section:has(a[href="/recognition"]) > div.relative.max-w-7xl { z-index:4!important; padding-top:1.1rem!important; padding-bottom:1.2rem!important; gap:.5rem!important; grid-template-columns:.56fr 1.44fr!important; min-height:178px; }
        main > section:has(a[href="/recognition"]) > div.relative.max-w-7xl::after { content:"View All Volunteers →"; position:absolute; right:2.5rem; top:.85rem; color:#ff5fb7; font-size:.72rem; font-weight:900; z-index:9; text-shadow:0 0 12px rgba(236,72,153,.42); }
        main > section:has(a[href="/recognition"]) p.text-yellow-300 { font-size:.68rem!important; letter-spacing:.14em!important; margin:0!important; color:#ffd43b!important; text-shadow:0 0 12px rgba(250,204,21,.22); }
        main > section:has(a[href="/recognition"]) h2 { font-size:clamp(1.85rem,2.65vw,2.8rem)!important; line-height:.98!important; margin-top:.42rem!important; letter-spacing:-.065em!important; text-shadow:0 3px 18px rgba(0,0,0,.56); }
        main > section:has(a[href="/recognition"]) p.text-slate-300 { max-width:24rem!important; line-height:1.5!important; font-size:.82rem!important; margin-top:.62rem!important; color:rgba(255,255,255,.86)!important; }
        main > section:has(a[href="/recognition"]) a[href="/recognition"].inline-block { background:linear-gradient(135deg,#fff0a3 0%,#facc15 45%,#c77900 100%)!important; border:1px solid rgba(255,239,160,.8)!important; box-shadow:0 13px 30px rgba(250,204,21,.34),inset 0 1px 0 rgba(255,255,255,.55)!important; border-radius:.65rem!important; padding:.62rem 1.12rem!important; font-size:.74rem!important; margin-top:.95rem!important; color:#1f1300!important; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end { position:relative; justify-content:flex-start!important; gap:0!important; padding-top:.9rem; padding-bottom:.05rem; min-height:170px; margin-left:-6rem; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end::before { content:""; position:absolute; left:4rem; right:2rem; top:44%; height:92px; z-index:-1; pointer-events:none; background:radial-gradient(ellipse at 44% 55%,rgba(255,214,87,.34),transparent 54%),linear-gradient(174deg,transparent 0 34%,rgba(255,236,145,.78) 40%,rgba(250,204,21,.25) 47%,transparent 60%); filter:drop-shadow(0 0 24px rgba(250,204,21,.34)); transform:rotate(-3deg); }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a { min-width:108px!important; margin-left:-5px; margin-right:-5px; transition:transform .22s ease; position:relative; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(1){transform:translateY(-34px);z-index:6;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(2){transform:translateY(-12px);z-index:5;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(3){transform:translateY(-22px);z-index:5;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(4){transform:translateY(18px);z-index:4;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(5){transform:translateY(24px);z-index:3;}
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a > div { position:relative; width:6.35rem!important; height:6.35rem!important; border-width:6px!important; box-shadow:0 0 0 8px rgba(0,0,0,.34),0 0 0 12px rgba(250,204,21,.12),0 20px 42px rgba(0,0,0,.48)!important; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(1) > div { width:7.7rem!important; height:7.7rem!important; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(2) > div, main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a:nth-child(3) > div { width:7.1rem!important; height:7.1rem!important; }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end h3 { margin-top:.48rem!important; font-size:.78rem!important; text-shadow:0 2px 10px rgba(0,0,0,.65); }
        main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end p { font-size:.62rem!important; margin-top:.05rem!important; }
        @media(max-width:900px){ main > section:has(a[href="/recognition"]) > div.relative.max-w-7xl{grid-template-columns:1fr!important;} main > section:has(a[href="/recognition"]) > div.relative.max-w-7xl::after{display:none;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end{margin-left:0;justify-content:center!important;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a{transform:none!important;margin:0;} main > section:has(a[href="/recognition"]) .flex.flex-wrap.items-end > a > div{width:5.75rem!important;height:5.75rem!important;} }
      ` }} />
      {children}
    </>
  );
}
