"use client";

import { useEffect, useState } from "react";
import SiteFooter from "../components/SiteFooter";
import { getSupabaseBrowserClient } from "../lib/supabaseBrowser";
import RecognitionWallPremium from "./RecognitionWallPremium";

const supabase = getSupabaseBrowserClient();

type EventRow = { id: string; title: string; date: string; location: string; image?: string | null; image_urls?: string[] | null };
type BusinessRow = { id: string; name: string; category?: string | null; image?: string | null; image_urls?: string[] | null };
type PersonRow = { id: string; name: string; title?: string | null; image?: string | null; photo?: string | null; picture?: string | null; count?: number };
type SponsorRow = { id: string; name: string; website?: string | null; logo_url?: string | null };

function firstImage(row: any) { if (Array.isArray(row?.image_urls) && row.image_urls.length > 0) return row.image_urls[0]; return row?.image || row?.photo || row?.picture || ""; }
function formatDate(value?: string | null) { if (!value) return ""; const d = new Date(`${String(value).split("T")[0]}T00:00:00`); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString(); }
function dateParts(value?: string | null) { const d = new Date(`${String(value || "").split("T")[0]}T00:00:00`); if (Number.isNaN(d.getTime())) return { month: "JUN", day: "--" }; return { month: d.toLocaleString("en-US", { month: "short" }).toUpperCase(), day: String(d.getDate()).padStart(2, "0") }; }
function Wave({ dark = false, flip = false }: { dark?: boolean; flip?: boolean }) { return <div className={`${flip ? "rotate-180" : ""} ${dark ? "text-[#050b18]" : "text-white"} -mb-px overflow-hidden`}><svg viewBox="0 0 1440 58" preserveAspectRatio="none" className="block h-9 md:h-14 w-full fill-current"><path d="M0 28C160 64 320 4 480 24C680 50 820 70 1030 28C1220-10 1340 14 1440 36V58H0V28Z" /></svg></div>; }
function Sparkles() { return <><span className="absolute left-[8%] top-[18%] h-2 w-2 rounded-full bg-pink-400/70 blur-[1px]" /><span className="absolute left-[30%] top-[12%] h-1.5 w-1.5 rounded-full bg-yellow-300/70" /><span className="absolute right-[16%] top-[20%] h-3 w-3 rounded-full bg-pink-500/50 blur-sm" /><span className="absolute right-[8%] bottom-[18%] h-1.5 w-1.5 rounded-full bg-yellow-300/70" /></>; }
function V2Header() { const links = [["Home","/home-v2"],["Events","/events"],["Radio","/radio"],["Businesses","/businesses"],["Team","/team"],["Contact","/contact"],["My Hub","/my-hub"],["Studio","/studio"]]; return <header className="absolute top-0 left-0 right-0 z-30 text-white"><div className="max-w-7xl mx-auto px-5 md:px-8 py-4 flex items-center justify-between gap-5"><a href="/home-v2" className="flex items-center gap-2 font-black"><img src="/sdtv-logo.png" alt="Seattle Desi TV" className="w-11 h-11 rounded-xl object-contain" /><span className="leading-tight text-sm md:text-base">SEATTLE<br />DESI TV</span></a><nav className="hidden lg:flex items-center gap-7 text-xs font-black"><a href="/home-v2" className="text-white relative after:absolute after:left-0 after:right-0 after:-bottom-3 after:h-1 after:rounded-full after:bg-pink-500">Home</a>{links.slice(1).map(([label,href]) => <a key={href} href={href} className="text-white/85 hover:text-white">{label}</a>)}</nav><a href="/login" className="bg-pink-600 hover:bg-pink-500 text-white px-5 py-2.5 rounded-xl text-xs font-black shadow-lg shadow-pink-600/30">Join / Sign In</a></div></header>; }
function EventCard({ event }: { event: EventRow }) { const image = firstImage(event); const p = dateParts(event.date); return <a href={`/events/${event.id}`} className="group bg-white rounded-xl overflow-hidden shadow-lg border border-slate-200 hover:-translate-y-1 hover:shadow-2xl transition block"><div className="relative h-36 md:h-40 bg-pink-50 overflow-hidden">{image ? <img src={image} alt={event.title} className="w-full h-full object-cover group-hover:scale-105 transition duration-300" /> : <div className="h-full grid place-items-center text-pink-600 font-black">SDTV Event</div>}<div className="absolute top-4 left-4 bg-white rounded-lg shadow-lg overflow-hidden text-center min-w-[52px]"><p className="bg-pink-600 text-white text-[10px] font-black px-2 py-1">{p.month}</p><p className="text-xl font-black px-2 py-1">{p.day}</p></div></div><div className="p-4"><h3 className="font-black text-base line-clamp-1">{event.title}</h3><p className="text-gray-600 text-xs mt-2">◷ {formatDate(event.date)}</p><p className="text-gray-600 text-xs mt-1">⌖ {event.location}</p><span className="inline-block mt-3 bg-pink-50 text-pink-600 rounded-full px-3 py-1 text-[10px] font-black">Cultural</span></div></a>; }
function Bars() { const bars = [35,52,44,74,60,88,64,45,63,78,53,90,68,43,56,74,48,66,83,54,41,70,58,90]; return <div className="flex items-end gap-1 h-20 mt-6">{bars.map((h, i) => <span key={i} className="flex-1 rounded-t bg-pink-500 animate-pulse shadow-lg shadow-pink-500/30" style={{ height: `${h}%`, animationDelay: `${i * 55}ms` }} />)}</div>; }

export default function HomeV2Page() {
  const [events, setEvents] = useState<EventRow[]>([]); const [businesses, setBusinesses] = useState<BusinessRow[]>([]); const [people, setPeople] = useState<PersonRow[]>([]); const [sponsors, setSponsors] = useState<SponsorRow[]>([]); const [counts, setCounts] = useState({ events: 0, businesses: 0, team: 0, radio: 0 });
  useEffect(() => { async function load() { const today = new Date().toISOString().split("T")[0]; const [er, br, tr, sr, profiles, completed, ec, bc, tc, rc] = await Promise.all([supabase.from("events").select("id,title,date,location,image,image_urls").eq("status", "approved").gte("date", today).order("date", { ascending: true }).limit(4), supabase.from("local_businesses").select("id,name,category,image,image_urls").eq("status", "approved").limit(5), supabase.from("team_members").select("id,name,title,image,photo,picture").limit(5), supabase.from("homepage_sponsors").select("id,name,website,logo_url").eq("active", true).limit(8), supabase.from("volunteer_onboarding_submissions").select("email,full_name,photo_url"), supabase.from("event_crew_assignments").select("id,user_email,user_id,coverage_completed,completed_at").eq("coverage_completed", true).order("completed_at", { ascending: false }).limit(250), supabase.from("events").select("id", { count: "exact", head: true }).eq("status", "approved"), supabase.from("local_businesses").select("id", { count: "exact", head: true }).eq("status", "approved"), supabase.from("team_members").select("id", { count: "exact", head: true }), supabase.from("radio_team_members").select("id", { count: "exact", head: true })]);
    setEvents(er.data || []); setBusinesses(br.data || []); setSponsors(sr.data || []); setCounts({ events: ec.count || 0, businesses: bc.count || 0, team: tc.count || 0, radio: rc.count || 0 });
    const byEmail: Record<string, any> = {}; (profiles.data || []).forEach((p: any) => { if (p.email) byEmail[p.email.toLowerCase()] = p; });
    const map: Record<string, PersonRow> = {}; (completed.data || []).forEach((r: any) => { const key = (r.user_email || r.user_id || r.id || "").toString().toLowerCase(); const profile = byEmail[key] || {}; if (!map[key]) map[key] = { id: key, name: profile.full_name || r.user_email || "SDTV Volunteer", photo: profile.photo_url, count: 0 }; map[key].count = (map[key].count || 0) + 10; });
    const realPeople = Object.values(map).sort((a,b)=>(b.count||0)-(a.count||0)); setPeople(realPeople.length ? realPeople.slice(0,5) : (tr.data || []).map((p:any)=>({ ...p, count: 100 })).slice(0,5));
  } load(); }, []);
  const heroImage = firstImage(events[0]) || "/hero-sdtv.png"; const sponsorRows = sponsors.length ? sponsors : [{ id: "one", name: "Community Partner" }, { id: "two", name: "Gold Sponsor" }, { id: "three", name: "Media Partner" }];
  return <main className="bg-white text-slate-950 overflow-hidden"><section className="relative bg-[#050b18] text-white overflow-hidden"><V2Header /><div className="absolute inset-0 bg-cover bg-center opacity-50 scale-105" style={{ backgroundImage: `url('${heroImage}')` }} /><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_20%,rgba(236,72,153,0.38),transparent_22rem),linear-gradient(90deg,#050b18_0%,rgba(5,11,24,0.96)_42%,rgba(5,11,24,0.56)_100%)]" /><Sparkles /><div className="relative max-w-7xl mx-auto px-6 md:px-10 pt-28 pb-12 md:pt-32 md:pb-16 grid lg:grid-cols-[0.95fr_1.05fr] gap-8 items-center min-h-[500px]"><div><h1 className="text-4xl md:text-6xl font-black leading-none">Seattle Desi TV</h1><p className="text-2xl md:text-4xl text-pink-400 font-black italic mt-3">Stories. Culture. <span className="text-yellow-300">Community.</span></p><p className="text-slate-200 leading-7 mt-5 max-w-xl text-sm md:text-base">Your community media platform for events, radio, businesses and volunteer impact across the Pacific Northwest.</p><div className="flex flex-wrap gap-3 mt-6"><a href="/events" className="bg-pink-600 hover:bg-pink-500 text-white px-5 py-3 rounded-lg font-black shadow-xl shadow-pink-600/25 text-sm">Explore Events</a><a href="/radio" className="border border-white/30 bg-white/10 hover:bg-white/15 text-white px-5 py-3 rounded-lg font-black backdrop-blur text-sm">▶ Listen Live</a></div></div><div className="hidden lg:block"><div className="rounded-[1.75rem] border border-white/15 bg-white/10 p-3 backdrop-blur-xl shadow-2xl"><div className="aspect-[16/9] rounded-[1.25rem] overflow-hidden bg-white/5"><img src={heroImage} alt="SDTV" className="w-full h-full object-cover" /></div></div></div></div><Wave /></section>
<section className="px-6 md:px-10 py-10 bg-white relative"><div className="max-w-7xl mx-auto"><div className="flex justify-between gap-4 mb-6"><h2 className="text-2xl md:text-3xl font-black">Upcoming Events <span className="text-pink-500">✦</span></h2><a href="/events" className="hidden md:block text-pink-600 font-black text-sm">View All Events →</a></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-5">{events.length ? events.map(e => <EventCard key={e.id} event={e} />) : [1,2,3,4].map(i => <div key={i} className="bg-white rounded-2xl p-8 shadow-xl border text-gray-500">Event card preview</div>)}</div></div></section>
<section className="relative bg-[#050b18] text-white overflow-hidden"><Wave flip dark /><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_45%,rgba(219,39,119,0.45),transparent_21rem)]" /><div className="absolute right-10 bottom-6 text-[11rem] md:text-[17rem] opacity-25 drop-shadow-[0_0_40px_rgba(236,72,153,0.65)]">🎙️</div><Sparkles /><div className="relative max-w-7xl mx-auto px-6 md:px-10 py-10 md:py-12 grid lg:grid-cols-[0.9fr_1.1fr] gap-8 items-center"><div><p className="text-pink-300 font-black uppercase tracking-[0.22em] text-xs">⌁ SDTV Radio</p><h2 className="text-3xl md:text-5xl font-black mt-3 leading-tight">Your Voice. Your Music. Your Community.</h2><p className="text-slate-300 mt-4 leading-7 text-sm md:text-base">Bollywood hits, community shows, talk, news and stories that connect us all.</p><a href="/radio" className="inline-block bg-pink-600 hover:bg-pink-500 text-white px-5 py-3 rounded-lg font-black text-sm mt-6">Listen Live Now ▶</a></div><div className="rounded-[1.5rem] border border-white/15 bg-white/10 p-5 md:p-6 backdrop-blur-xl shadow-2xl max-w-2xl"><span className="bg-pink-600 text-white px-3 py-1 rounded-full text-[10px] font-black">● LIVE</span><h3 className="text-xl font-black mt-3">SDTV Radio Live</h3><p className="text-slate-300 text-sm">Best of Bollywood & Community Voices</p><Bars /></div></div><Wave /></section>
<section className="bg-white px-6 md:px-10 py-10"><div className="max-w-7xl mx-auto"><h2 className="text-2xl md:text-3xl font-black mb-6">Featured Videos <span className="text-pink-500">✦</span></h2><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-5">{["Community Stories","Event Highlights","Volunteer Stories","Studio Talk"].map((v,i)=><a key={v} href="https://www.youtube.com/@SeattleDesiTV/videos" className="group"><div className="h-36 rounded-xl overflow-hidden bg-slate-950 relative shadow-xl"><img src={i===0?heroImage:"/hero-sdtv.png"} alt={v} className="w-full h-full object-cover opacity-80 group-hover:scale-105 transition" /><span className="absolute inset-0 grid place-items-center"><b className="w-10 h-10 bg-white/90 text-pink-600 rounded-full grid place-items-center">▶</b></span></div><h3 className="font-black mt-3 text-sm">{v}</h3></a>)}</div></div></section>
<RecognitionWallPremium people={people} />
<section className="bg-gradient-to-br from-orange-50 via-white to-pink-50 px-6 md:px-10 py-10"><div className="max-w-7xl mx-auto"><h2 className="text-2xl md:text-3xl font-black mb-6">SDTV Businesses <span className="text-pink-500">✦</span></h2><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-5">{businesses.slice(0,5).map(b=>{const img=firstImage(b);return <a key={b.id} href="/businesses" className="bg-white rounded-xl p-4 shadow-xl border hover:-translate-y-1 transition"><div className="h-20 rounded-xl bg-slate-50 grid place-items-center mb-3 overflow-hidden">{img?<img src={img} alt={b.name} className="max-h-16 max-w-full object-contain"/>:<span className="text-pink-600 font-black">SDTV</span>}</div><h3 className="font-black text-sm">{b.name}</h3><p className="text-gray-500 text-xs">{b.category || "Local Business"}</p></a>})}</div></div></section>
<section className="relative bg-[#050b18] text-white px-6 md:px-10 py-10"><div className="max-w-7xl mx-auto"><h2 className="text-2xl md:text-3xl font-black">Our Impact <span className="text-pink-400">✦</span></h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{[["📅",counts.events+"+","Events Published"],["👥",counts.team+"+","Team Members"],["🤝",counts.businesses+"+","Business Partners"],["🎙️",counts.radio+"+","Radio Hosts"]].map(([i,v,l])=><div key={l} className="rounded-xl border border-white/10 bg-white/5 p-5 backdrop-blur"><p className="text-2xl">{i}</p><p className="text-3xl font-black mt-2">{v}</p><p className="text-slate-300 text-xs">{l}</p></div>)}</div></div></section>
<section className="bg-white px-6 md:px-10 py-8"><div className="max-w-7xl mx-auto"><h2 className="text-2xl font-black mb-5">Our Sponsors <span className="text-pink-500">✦</span></h2><div className="flex gap-5 overflow-x-auto pb-4">{sponsorRows.map(s=><a key={s.id} href={s.website||"/contact?interest=sponsorship"} className="min-w-[190px] bg-white border rounded-xl p-4 shadow-lg text-center"><div className="h-14 grid place-items-center">{s.logo_url?<img src={s.logo_url} alt={s.name} className="max-h-12 max-w-[150px] object-contain"/>:<span className="font-black text-lg text-slate-700">{s.name}</span>}</div></a>)}</div></div></section>
<section className="bg-[#050b18] text-white px-6 md:px-10 py-8"><div className="max-w-7xl mx-auto rounded-2xl border border-white/10 bg-gradient-to-r from-pink-600/25 via-white/5 to-yellow-400/10 p-7 flex flex-col md:flex-row md:items-center md:justify-between gap-5"><div><h2 className="text-2xl md:text-3xl font-black">Let's Build Together <span className="text-pink-300">✦</span></h2><p className="text-slate-300 mt-1 text-sm">Have a question, partnership idea, or want to get involved?</p></div><div className="flex flex-wrap gap-3"><a href="/contact" className="bg-pink-600 hover:bg-pink-500 text-white px-5 py-3 rounded-lg font-black text-sm">Contact Us</a><a href="/contact?interest=volunteer" className="border border-white/30 px-5 py-3 rounded-lg font-black text-sm">Join as Volunteer</a></div></div></section><SiteFooter /></main>;
}
