"use client";

import { useMemo, useState } from "react";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";
import OfferCard from "../components/business-offers/OfferCard";
import { useBusinessOffers } from "../hooks/useBusinessOffers";

export default function OffersPage() { const { offers, loading, error } = useBusinessOffers("public"); const [search, setSearch] = useState(""); const visible = useMemo(() => { const query = search.trim().toLowerCase(); return offers.filter((offer) => !query || `${offer.title} ${offer.description || ""} ${offer.local_businesses?.name || ""} ${offer.local_businesses?.category || ""}`.toLowerCase().includes(query)); }, [offers, search]); return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader /><section className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto max-w-7xl"><p className="font-black uppercase tracking-wide text-pink-300">Seattle Desi Marketplace</p><h1 className="mt-2 text-5xl font-black">Local Offers</h1><p className="mt-3 max-w-2xl text-slate-300">Discover current offers from approved businesses in the Seattle Desi TV directory.</p></div></section><section className="mx-auto max-w-7xl px-6 py-10"><div className="mb-7 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_auto]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search offers or businesses..." className="rounded-xl border p-3"/><a href="/businesses" className="rounded-xl border px-5 py-3 text-center font-black">Business Directory</a></div>{loading ? <div className="rounded-2xl bg-white p-8">Loading offers...</div> : error ? <div className="rounded-2xl bg-red-50 p-6 font-bold text-red-700">{error}</div> : visible.length ? <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{visible.map((offer) => <OfferCard key={offer.id} offer={offer}/>)}</div> : <div className="rounded-2xl border bg-white p-8 text-slate-500">No active offers found.</div>}</section><SiteFooter /></main>; }
