"use client";
import { useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { usePublishingPipeline } from "../../../hooks/usePublishingPipeline";
import { AVAILABLE_PUBLISHING_CHANNELS } from "../../../lib/publishing/services/publishingPipelineService";
import type { PublishingChannel } from "../../../lib/publishing/repositories/publishingPipelineRepository";
export default function PublishingPipelineWorkspace({ supabase, publicationId }: { supabase: SupabaseClient; publicationId: string }) {
  const pipeline = usePublishingPipeline(supabase, publicationId); const [channels, setChannels] = useState<Set<PublishingChannel>>(new Set(["website", "newsletter", "pdf"])); const [scheduledAt, setScheduledAt] = useState("");
  function toggle(channel: PublishingChannel) { setChannels((current) => { const next = new Set(current); if (next.has(channel)) next.delete(channel); else next.add(channel); return next; }); }
  function publish(outputId: string) { const output = pipeline.outputs.find((item) => item.id === outputId); if (!output || !window.confirm(`Confirm ${output.status === "failed" ? "retry" : "publishing handoff"} for ${output.channel}?`)) return; void pipeline.publish(output); }
  return <div className="grid gap-5"><section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">Publishing pipeline</h2><p className="mt-1 text-sm text-slate-600">Generate channel outputs now or schedule them. External channels remain manual handoffs until adapters are configured.</p><div className="mt-4 flex flex-wrap gap-2">{AVAILABLE_PUBLISHING_CHANNELS.map((channel) => <label key={channel} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm font-black ${channels.has(channel) ? "border-pink-400 bg-pink-50 text-pink-700" : "border-slate-200"}`}><input type="checkbox" checked={channels.has(channel)} onChange={() => toggle(channel)} className="mr-2" />{channel}</label>)}</div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="flex-1 text-xs font-black uppercase text-slate-500">Optional schedule<input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm font-normal normal-case" /></label><button type="button" disabled={pipeline.busy || !channels.size} onClick={() => void pipeline.prepare([...channels], scheduledAt ? new Date(scheduledAt).toISOString() : null)} className="self-end rounded-xl bg-pink-600 px-5 py-3 font-black text-white disabled:opacity-50">{pipeline.busy ? "Working…" : scheduledAt ? "Schedule outputs" : "Generate outputs"}</button></div>{pipeline.error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{pipeline.error}</p>}</section>
    <section className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="text-xl font-black">Channel status</h3><button type="button" onClick={() => void pipeline.refresh()} className="text-sm font-black text-pink-600">Refresh</button></div>{pipeline.loading ? <p className="mt-4 text-slate-500">Loading pipeline…</p> : <div className="mt-4 grid gap-3 md:grid-cols-2">{pipeline.outputs.map((output) => <article key={output.id} className="rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><p className="font-black capitalize">{output.channel}</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase">{output.status}</span></div>{output.scheduled_at && <p className="mt-2 text-xs text-slate-500">Scheduled {new Date(output.scheduled_at).toLocaleString()}</p>}{output.last_error && <p className="mt-2 text-sm text-red-600">{output.last_error}</p>}<div className="mt-3 flex gap-2">{["ready", "failed"].includes(output.status) && <button type="button" disabled={pipeline.busy} onClick={() => publish(output.id)} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white">{output.status === "failed" ? "Retry" : "Confirm handoff"}</button>}{output.status === "scheduled" && <button type="button" disabled={pipeline.busy} onClick={() => void pipeline.cancel(output)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-black text-red-700">Cancel</button>}</div></article>)}{!pipeline.outputs.length && <p className="text-sm text-slate-500">No outputs generated yet.</p>}</div>}</section>
    <section className="rounded-3xl border bg-white p-5"><h3 className="text-xl font-black">Publishing history</h3><div className="mt-4 divide-y">{pipeline.attempts.map((attempt) => <div key={attempt.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><div><span className="font-black capitalize">{attempt.channel}</span> · {attempt.action}</div><div className="text-right"><span className="font-bold uppercase text-slate-500">{attempt.status}</span><p className="text-xs text-slate-400">{new Date(attempt.attempted_at).toLocaleString()}</p></div></div>)}{!pipeline.attempts.length && <p className="text-sm text-slate-500">No publishing attempts recorded.</p>}</div></section></div>;
}
