"use client";
import { useCallback,useEffect,useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabaseBrowser";
import { isAdminRole,resolveUserRole } from "../lib/roles";
import { MatrimonyService } from "../lib/matrimony/services/matrimonyService";
import type { MatrimonyAccessRequest,MatrimonyPricing,MatrimonyProfileInput,MatrimonyProfileWithContact } from "../lib/matrimony/types";
export function useMatrimony(mode:"member"|"admin"){
 const [user,setUser]=useState<{id:string;email:string}|null>(null),[profile,setProfile]=useState<MatrimonyProfileWithContact|null>(null),[profiles,setProfiles]=useState<MatrimonyProfileWithContact[]>([]),[access,setAccess]=useState<MatrimonyAccessRequest|null>(null),[requests,setRequests]=useState<MatrimonyAccessRequest[]>([]),[pricing,setPricing]=useState<MatrimonyPricing|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const auth=await getSupabaseBrowserClient().auth.getUser();const current=auth.data.user;if(!current)throw new Error("Please log in to use SDTV Matrimony.");setUser({id:current.id,email:current.email||""});if(mode==="admin"){if(!isAdminRole(await resolveUserRole(getSupabaseBrowserClient(),current)))throw new Error("Admin access is required.");setProfiles(await MatrimonyService.listAdminProfiles());setRequests(await MatrimonyService.listAdminAccess());setPricing(await MatrimonyService.getPricing(true));}else{const [own,ownAccess,price]=await Promise.all([MatrimonyService.getOwnProfile(current.id),MatrimonyService.getOwnAccess(current.id),MatrimonyService.getPricing()]);setProfile(own);setAccess(ownAccess);setPricing(price);const active=ownAccess?.status==="active"&&!!ownAccess.access_expires_at&&new Date(ownAccess.access_expires_at)>new Date();setProfiles(active?await MatrimonyService.listVisible():[]);}}catch(cause){setError(cause instanceof Error?cause.message:"Matrimony could not be loaded.");}finally{setLoading(false);}},[mode]);
 useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[refresh]);
 async function run(task:()=>Promise<unknown>){setSaving(true);setError("");try{await task();await refresh();}catch(cause){setError(cause instanceof Error?cause.message:"The matrimony action could not be completed.");throw cause;}finally{setSaving(false);}}
 return{user,profile,profiles,access,requests,pricing,loading,saving,error,refresh,saveProfile:(input:MatrimonyProfileInput,id?:string)=>run(()=>MatrimonyService.saveProfile(input,user!.id,id)),requestAccess:(reason:string)=>run(()=>MatrimonyService.requestAccess(user!.id,user!.email,reason)),upload:(file:File)=>MatrimonyService.uploadPhoto(file,user!.id),reviewProfile:(id:string,decision:string,notes:string)=>run(()=>MatrimonyService.reviewProfile(id,decision,notes)),reviewAccess:(id:string,decision:string,price:number|null,duration:number|null,notes:string,link:string)=>run(()=>MatrimonyService.reviewAccess(id,decision,price,duration,notes,link)),completePayment:(id:string,reference:string)=>run(()=>MatrimonyService.completePayment(id,reference)),updatePricing:(changes:Partial<MatrimonyPricing>)=>run(()=>MatrimonyService.updatePricing(changes))};
}
