"use client";
import { useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { uploadFileToCloudinary } from "../lib/cloudinaryUpload";
import { defaultSocialLaunchCaptions, publishSocialLaunch, renderSocialLaunchImage, type SocialLaunchChannel } from "../lib/publishing/services/socialLaunchService";
import { usePublicationPreview } from "./usePublicationPreview";

export function useSocialLaunch(supabase: SupabaseClient, publicationId: string) {
  const previewState = usePublicationPreview(supabase, publicationId); const [captions, setCaptions] = useState<Record<SocialLaunchChannel, string> | null>(null); const [files, setFiles] = useState<Partial<Record<SocialLaunchChannel, File>>>({}); const [urls, setUrls] = useState<Partial<Record<SocialLaunchChannel, string>>>({}); const [approvals, setApprovals] = useState<Partial<Record<SocialLaunchChannel, string>>>({}); const [busy, setBusy] = useState<SocialLaunchChannel | "all" | "">(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!previewState.preview || captions) return; const timer = setTimeout(() => setCaptions(defaultSocialLaunchCaptions(previewState.preview!)), 0); return () => clearTimeout(timer); }, [captions, previewState.preview]);
  useEffect(() => () => Object.values(urls).forEach((url) => { if (url?.startsWith("blob:")) URL.revokeObjectURL(url); }), [urls]);
  const signatures = useMemo(() => ({ instagram: `${urls.instagram || ""}|${captions?.instagram || ""}`, facebook: `${urls.facebook || ""}|${captions?.facebook || ""}`, linkedin: `${urls.linkedin || ""}|${captions?.linkedin || ""}` }), [captions, urls]);
  function updateCaption(channel: SocialLaunchChannel, value: string) { setCaptions((current) => current ? { ...current, [channel]: value } : current); setApprovals((current) => ({ ...current, [channel]: undefined })); }
  async function generate(channel: SocialLaunchChannel) { if (!previewState.preview) return; setBusy(channel); setError(""); try { const file = await renderSocialLaunchImage(previewState.preview, channel); if (urls[channel]?.startsWith("blob:")) URL.revokeObjectURL(urls[channel]!); setFiles((current) => ({ ...current, [channel]: file })); setUrls((current) => ({ ...current, [channel]: URL.createObjectURL(file) })); setApprovals((current) => ({ ...current, [channel]: undefined })); setMessage(`${channel} image generated. Review and upload it.`); } catch (next) { setError(next instanceof Error ? next.message : "Could not generate image."); } finally { setBusy(""); } }
  async function upload(channel: SocialLaunchChannel) { const file = files[channel]; if (!file) return setError("Generate the launch image first."); setBusy(channel); setError(""); try { const url = await uploadFileToCloudinary(file); if (urls[channel]?.startsWith("blob:")) URL.revokeObjectURL(urls[channel]!); setUrls((current) => ({ ...current, [channel]: url })); setApprovals((current) => ({ ...current, [channel]: undefined })); setMessage(`${channel} image uploaded. Approve the exact image and caption before publishing.`); } catch (next) { setError(next instanceof Error ? next.message : "Could not upload image."); } finally { setBusy(""); } }
  function approve(channel: SocialLaunchChannel, approved: boolean) { setApprovals((current) => ({ ...current, [channel]: approved ? signatures[channel] : undefined })); }
  async function publish(channel: SocialLaunchChannel) { const imageUrl = urls[channel]; const caption = captions?.[channel] || ""; if (!imageUrl?.startsWith("https://")) return setError("Upload the image before publishing."); if (approvals[channel] !== signatures[channel]) return setError("Approve the final image and caption first."); setBusy(channel); setError(""); try { await publishSocialLaunch(supabase, publicationId, channel, imageUrl, caption); setMessage(`Published to ${channel}.`); } catch (next) { setError(next instanceof Error ? next.message : `Could not publish to ${channel}.`); } finally { setBusy(""); } }
  return { ...previewState, captions, files, urls, approvals, signatures, busy, error: error || previewState.error, message, updateCaption, generate, upload, approve, publish };
}
