"use client";
import { useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PublicationAiPrompt } from "../../lib/publishing/repositories/publicationAiRepository";
import { getPublicationAiPrompts, savePublicationAiPrompt } from "../../lib/publishing/services/promptService";
export default function PromptManager({ supabase }: { supabase: SupabaseClient }) {
  const [prompts, setPrompts] = useState<PublicationAiPrompt[]>([]); const [status, setStatus] = useState("Loading prompts…");
  useEffect(() => { const timer = setTimeout(() => void getPublicationAiPrompts(supabase).then((rows) => { setPrompts(rows); setStatus(""); }).catch((error) => setStatus(error instanceof Error ? error.message : "Could not load prompts.")), 0); return () => clearTimeout(timer); }, [supabase]);
  function change(id: string, changes: Partial<PublicationAiPrompt>) { setPrompts((current) => current.map((prompt) => prompt.id === id ? { ...prompt, ...changes } : prompt)); }
  async function save(prompt: PublicationAiPrompt) { setStatus("Saving prompt…"); try { const saved = await savePublicationAiPrompt(supabase, prompt); change(saved.id, saved); setStatus(`Saved ${saved.name} · version ${saved.version}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not save prompt."); } }
  return <details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-black">Prompt management</summary><p className="mt-2 text-sm text-slate-500">Administrator prompts are versioned whenever they are saved.</p>{status && <p className="mt-3 text-sm font-bold text-purple-700">{status}</p>}<div className="mt-4 grid gap-4">{prompts.map((prompt) => <div key={prompt.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{prompt.name}</p><p className="text-xs uppercase text-slate-400">{prompt.target_type} · v{prompt.version}</p></div><label className="text-sm font-bold"><input type="checkbox" checked={prompt.active} onChange={(event) => change(prompt.id, { active: event.target.checked })} /> Active</label></div><textarea aria-label={`${prompt.name} system prompt`} value={prompt.system_prompt} onChange={(event) => change(prompt.id, { system_prompt: event.target.value })} rows={3} className="mt-3 w-full rounded-xl border p-3 text-sm" /><textarea aria-label={`${prompt.name} user template`} value={prompt.user_prompt_template} onChange={(event) => change(prompt.id, { user_prompt_template: event.target.value })} rows={2} className="mt-2 w-full rounded-xl border p-3 text-sm" /><button type="button" onClick={() => void save(prompt)} className="mt-3 rounded-lg bg-slate-950 px-4 py-2 text-xs font-black text-white">Save prompt</button></div>)}</div></details>;
}
