import { getSupabaseBrowserClient } from "../../supabaseBrowser";
import type { BusinessOffer, BusinessOfferInput, OfferBusiness } from "../types";

const supabase = getSupabaseBrowserClient();
const OFFER_SELECT = "id,business_id,title,description,terms,offer_code,destination_url,image_url,starts_at,ends_at,status,requested_placement,is_premium,premium_rank,is_featured,featured_rank,is_homepage_hero,homepage_rank,quoted_price_cents,payment_status,payment_reference,created_by,approved_at,created_at,updated_at,local_businesses(id,name,address,website,category,image,image_urls)";

export async function listPublicOffers() { const { data, error } = await supabase.from("business_offers").select(OFFER_SELECT).eq("status", "approved").lte("starts_at", new Date().toISOString().slice(0, 10)).or(`ends_at.is.null,ends_at.gte.${new Date().toISOString().slice(0, 10)}`).order("is_featured", { ascending: false }).order("featured_rank").order("is_premium", { ascending: false }).order("premium_rank").order("starts_at", { ascending: false }); if (error) throw error; return (data || []) as unknown as BusinessOffer[]; }
export async function listOffersForBusinesses(businessIds: string[]) { if (!businessIds.length) return []; const { data, error } = await supabase.from("business_offers").select(OFFER_SELECT).in("business_id", businessIds).order("created_at", { ascending: false }); if (error) throw error; return (data || []) as unknown as BusinessOffer[]; }
export async function listManagedBusinesses(userId: string) { const columns = "id,name,address,website,category,image,image_urls"; const [submitted, managed] = await Promise.all([supabase.from("local_businesses").select(columns).eq("created_by", userId).order("name"), supabase.from("business_managers").select(`local_businesses(${columns})`).eq("user_id", userId).eq("active", true)]); if (submitted.error) throw submitted.error; if (managed.error) throw managed.error; const map = new Map<string, OfferBusiness>(); ((submitted.data || []) as OfferBusiness[]).forEach((row) => map.set(row.id, row)); (managed.data || []).forEach((row) => { const related = row.local_businesses as unknown as OfferBusiness | OfferBusiness[] | null; const business = Array.isArray(related) ? related[0] : related; if (business?.id) map.set(business.id, business); }); return Array.from(map.values()); }
export async function listAllOffers() { const { data, error } = await supabase.from("business_offers").select(OFFER_SELECT).order("created_at", { ascending: false }); if (error) throw error; return (data || []) as unknown as BusinessOffer[]; }
export async function createOffer(input: BusinessOfferInput, userId: string) { const { data, error } = await supabase.from("business_offers").insert({ ...input, created_by: userId, status: input.status || "pending" }).select(OFFER_SELECT).single(); if (error) throw error; return data as unknown as BusinessOffer; }
export async function updateOwnerOffer(id: string, input: Partial<BusinessOfferInput>) { const { data, error } = await supabase.from("business_offers").update({ ...input, updated_at: new Date().toISOString() }).eq("id", id).select(OFFER_SELECT).single(); if (error) throw error; return data as unknown as BusinessOffer; }
export async function deleteOwnerOffer(id: string) { const { error } = await supabase.from("business_offers").delete().eq("id", id); if (error) throw error; }
export async function updateOfferAdmin(id: string, changes: Record<string, unknown>) { const { data, error } = await supabase.from("business_offers").update({ ...changes, updated_at: new Date().toISOString() }).eq("id", id).select(OFFER_SELECT).single(); if (error) throw error; return data as unknown as BusinessOffer; }
