"use client";
import StudioHeader from "../../components/StudioHeader";
import { useAdminDigestArchive } from "../../hooks/useAdminDigestArchive";

const when = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
const total = (counts: Record<string, unknown>) => {
  const submissions = counts?.submissions && typeof counts.submissions === "object" ? Object.values(counts.submissions as Record<string, unknown>).reduce<number>((sum, value) => sum + Number(value || 0), 0) : 0;
  return Number(counts?.registrations || 0) + Number(counts?.volunteerRequests || 0) + Number(counts?.teamMemberRequests || 0) + submissions;
};

export default function AdminDigestsPage() {
  const { deliveries, loading, sending, error, message, refresh, sendTest } = useAdminDigestArchive();
  return <main className="min-h-screen bg-slate-100 text-slate-950"><StudioHeader /><section className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="font-black uppercase tracking-wide text-pink-600">Communications</p><h1 className="mt-2 text-4xl font-black">Daily Digest Archive</h1><p className="mt-2 max-w-3xl text-slate-600">Delivery history and totals for scheduled administrator activity emails. Full email bodies and sensitive submission details are not stored.</p></div><div className="flex gap-3"><button onClick={refresh} disabled={loading} className="rounded-xl border bg-white px-5 py-3 font-black">Refresh</button><button onClick={sendTest} disabled={sending} className="rounded-xl bg-pink-600 px-5 py-3 font-black text-white disabled:opacity-60">{sending ? "Sending…" : "Send test digest"}</button></div></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-800">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-4 font-bold text-green-800">{message}</p>}<div className="mt-7 grid gap-4">{deliveries.map((delivery) => <article key={delivery.id} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-pink-50 px-3 py-1 text-xs font-black uppercase text-pink-700">{delivery.delivery_type}</span><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${delivery.status === "sent" ? "bg-green-50 text-green-700" : delivery.status === "failed" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{delivery.status}</span></div><h2 className="mt-3 text-xl font-black">{delivery.subject}</h2><p className="mt-1 text-sm text-slate-500">To {delivery.recipient} · Created {when(delivery.created_at)} · Sent {when(delivery.sent_at)}</p></div><div className="rounded-2xl bg-slate-950 px-5 py-3 text-center text-white"><p className="text-xs font-black uppercase text-pink-300">Updates</p><p className="text-3xl font-black">{total(delivery.counts || {})}</p></div></div><div className="mt-4 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm md:grid-cols-3"><p><b>Report start</b><br />{when(delivery.report_from)}</p><p><b>Report end</b><br />{when(delivery.report_to)}</p><p><b>Triggered by</b><br />{delivery.triggered_by || "—"}</p>{delivery.provider_email_id && <p className="md:col-span-3"><b>Provider email ID</b><br />{delivery.provider_email_id}</p>}{delivery.error_message && <p className="md:col-span-3 text-red-700"><b>Failure</b><br />{delivery.error_message}</p>}</div></article>)}{!loading && deliveries.length === 0 && <p className="rounded-2xl bg-white p-7 text-slate-500">No digest emails have been archived yet.</p>}{loading && <p className="rounded-2xl bg-white p-7">Loading digest archive…</p>}</div></section></main>;
}
