"use client";
import { useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { usePublicationPreview } from "../../../hooks/usePublicationPreview";
import type { PublicationPreviewChannel } from "../../../lib/publishing/preview/types";
import { previewFileName } from "../../../lib/publishing/services/previewService";
import PublicationChannelPreview from "./PublicationChannelPreview";
const channels: PublicationPreviewChannel[] = ["website", "newsletter", "instagram", "facebook", "linkedin", "mobile", "print"];
function download(content: string, type: string, name: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
function escapeHtml(value: string | null) { return String(value || "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] || character); }
export default function PublicationPreviewWorkspace({ supabase, publicationId }: { supabase: SupabaseClient; publicationId: string }) {
  const state = usePublicationPreview(supabase, publicationId); const [channel, setChannel] = useState<PublicationPreviewChannel>("website");
  if (state.loading) return <div className="rounded-3xl bg-white p-8 font-bold">Building complete publication preview…</div>;
  if (state.error || !state.preview) return <div className="rounded-3xl bg-red-50 p-6 font-bold text-red-700">{state.error || "Preview unavailable."}</div>;
  const model = state.preview;
  function exportHtml() {
    const cover = model.publication.cover_image_url || model.sections.find((section) => section.section_key === "cover")?.items.find((item) => item.image_url)?.image_url;
    const sections = model.sections.filter((section) => section.section_key !== "cover").map((section) => `<section class="${escapeHtml(section.section_key)}"><h2>${escapeHtml(section.title)}</h2><p>${escapeHtml(section.introduction)}</p><div class="grid">${section.items.map((item) => `<article>${item.image_url ? `<img src="${escapeHtml(item.image_url)}" alt="${escapeHtml(item.title)}">` : ""}<div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p>${item.destination_url ? `<a href="${escapeHtml(item.destination_url)}">Learn more →</a>` : ""}</div></article>`).join("")}</div></section>`).join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(model.publication.name)}</title><style>body{margin:0;font:16px/1.6 Arial,sans-serif;color:#0f172a;background:#f8fafc}header{min-height:420px;padding:48px;box-sizing:border-box;display:flex;flex-direction:column;justify-content:end;color:white;background:linear-gradient(0deg,rgba(2,6,23,.92),rgba(2,6,23,.2))${cover ? `,url('${escapeHtml(cover)}') center/cover` : ",#831843"}}header h1{font-size:48px;margin:8px 0}main{max-width:1100px;margin:auto;padding:32px}section{margin:32px 0}h2{border-bottom:3px solid #db2777}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}article{overflow:hidden;border:1px solid #e2e8f0;border-radius:18px;background:white}article img{width:100%;height:180px;object-fit:cover}article div{padding:18px}a{color:#be185d;font-weight:bold}.get_involved{padding:28px;border-radius:24px;background:#020617;color:white}.statistics h3{font-size:24px;color:#db2777}@media(max-width:600px){header{min-height:320px;padding:24px}header h1{font-size:36px}main{padding:18px}}@media print{body{background:white}article,section{break-inside:avoid}}</style></head><body><header><small>SEATTLE DESI TV</small><h1>${escapeHtml(model.publication.name)}</h1><strong>${escapeHtml(model.publication.edition_label)}</strong><p>${escapeHtml(model.publication.description)}</p></header><main>${sections}</main></body></html>`;
    download(html, "text/html", previewFileName(model.publication.name, "html"));
  }
  return <div><div className="mb-5 flex flex-col gap-3 rounded-2xl bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{channels.map((item) => <button key={item} type="button" onClick={() => setChannel(item)} className={`rounded-lg px-3 py-2 text-xs font-black uppercase ${channel === item ? "bg-slate-950 text-white" : "bg-slate-100"}`}>{item}</button>)}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void state.refresh()} className="rounded-lg border px-3 py-2 text-xs font-black">Refresh</button><button type="button" onClick={() => download(JSON.stringify(model, null, 2), "application/json", previewFileName(model.publication.name, "json"))} className="rounded-lg border px-3 py-2 text-xs font-black">JSON</button><button type="button" onClick={exportHtml} className="rounded-lg border px-3 py-2 text-xs font-black">HTML</button><button type="button" onClick={() => window.print()} className="rounded-lg bg-pink-600 px-3 py-2 text-xs font-black text-white">Print / Save PDF</button></div></div><PublicationChannelPreview model={model} channel={channel} /></div>;
}
