import type { SupabaseClient } from "@supabase/supabase-js";
import { buildPublicationPreview } from "./previewService";
import { createCampaign, createOutputs, listAttempts, listOutputs, recordAttempt, updateOutput, type PublicationOutputRecord, type PublishingChannel } from "../repositories/publishingPipelineRepository";
import { getPublishingAdapter } from "../adapters/registry";
export const AVAILABLE_PUBLISHING_CHANNELS: PublishingChannel[] = ["website", "newsletter", "instagram", "facebook", "linkedin", "pdf", "email"];
async function currentUser(supabase: SupabaseClient) { const session = await supabase.auth.getSession(); const user = session.data.session?.user; if (!user) throw new Error("Please log in to use the publishing pipeline."); return user; }
export async function getPublishingPipeline(supabase: SupabaseClient, publicationId: string) { const [outputs, attempts] = await Promise.all([listOutputs(supabase, publicationId), listAttempts(supabase, publicationId)]); return { outputs, attempts }; }
export async function preparePublishingOutputs(supabase: SupabaseClient, publicationId: string, channels: PublishingChannel[], scheduledAt?: string | null) { const user = await currentUser(supabase); if (!channels.length) throw new Error("Select at least one publishing channel."); const preview = await buildPublicationPreview(supabase, publicationId); const campaignId = await createCampaign(supabase, publicationId, `${preview.publication.name} publishing run`, channels, user.id, scheduledAt); const now = new Date().toISOString(); const outputs = await createOutputs(supabase, channels.map((channel) => ({ publication_id: publicationId, campaign_id: campaignId, output_type: channel === "pdf" ? "file" : "channel", channel, status: scheduledAt ? "scheduled" : "ready", content: preview, scheduled_at: scheduledAt || null, updated_by: user.id, last_attempt_at: now }))); await Promise.all(outputs.map((output) => recordAttempt(supabase, { publication_id: publicationId, campaign_id: campaignId, output_id: output.id, channel: output.channel, action: scheduledAt ? "schedule" : "generate", status: "completed", request_snapshot: { scheduledAt: scheduledAt || null }, response_snapshot: { outputId: output.id, status: output.status }, attempted_by: user.id }))); return outputs; }
export async function publishOutput(supabase: SupabaseClient, output: PublicationOutputRecord, confirmed: boolean) { const user = await currentUser(supabase); if (!confirmed) throw new Error("Explicit publishing confirmation is required."); const adapter = getPublishingAdapter(output.channel); const status = "manual_handoff"; const now = new Date().toISOString(); const saved = await updateOutput(supabase, output.id, { status, attempt_count: output.attempt_count + 1, last_attempt_at: now, last_error: null, updated_by: user.id }); await recordAttempt(supabase, { publication_id: output.publication_id, campaign_id: output.campaign_id, output_id: output.id, channel: output.channel, action: output.status === "failed" ? "retry" : "publish", status, request_snapshot: { confirmed }, response_snapshot: { status, deliveryMode: adapter.deliveryMode, configurationKey: adapter.configurationKey, reason: "Automatic external delivery is not enabled." }, attempted_by: user.id }); return saved; }
export async function cancelScheduledOutput(supabase: SupabaseClient, output: PublicationOutputRecord) { const user = await currentUser(supabase); const saved = await updateOutput(supabase, output.id, { status: "cancelled", scheduled_at: null, updated_by: user.id }); await recordAttempt(supabase, { publication_id: output.publication_id, campaign_id: output.campaign_id, output_id: output.id, channel: output.channel, action: "cancel", status: "cancelled", attempted_by: user.id }); return saved; }
