"use client";

import Script from "next/script";
import { useEffect, useRef, useState, type FormEvent } from "react";
import SiteFooter from "../../components/SiteFooter";
import SiteHeader from "../../components/SiteHeader";
import { useCurrentSite } from "../../lib/sites/SiteContext";

declare global { interface Window { turnstile?: any } }
const siteKey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY || process.env.NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY || "";
const blank = { organization_id: "", event_id: "", organization_name: "", contact_name: "", contact_email: "", contact_phone: "", event_title: "", event_date: "", event_location: "", event_url: "", event_type: "nonprofit_community", notes: "" };

export default function MediaPartnerRequestPage() {
  const site = useCurrentSite();
  const [form, setForm] = useState(blank); const [flyer, setFlyer] = useState<File | null>(null); const [captchaToken, setCaptchaToken] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [organizations, setOrganizations] = useState<any[]>([]); const [events, setEvents] = useState<any[]>([]);
  const turnstileRef = useRef<HTMLDivElement | null>(null); const widgetId = useRef<string | null>(null);
  function renderTurnstile() { if (!siteKey || !turnstileRef.current || !window.turnstile || widgetId.current) return; widgetId.current = window.turnstile.render(turnstileRef.current, { sitekey: siteKey, callback: (token: string) => setCaptchaToken(token), "expired-callback": () => setCaptchaToken("") }); }
  useEffect(() => { const timer = window.setInterval(() => { renderTurnstile(); if (widgetId.current) window.clearInterval(timer); }, 300); return () => window.clearInterval(timer); }, []);
  useEffect(() => { void Promise.all([fetch("/api/mobile/v1/organizations?limit=100", { cache: "no-store" }).then((response) => response.json()), fetch("/api/mobile/v1/events?limit=100", { cache: "no-store" }).then((response) => response.json())]).then(([organizationResult, eventResult]) => { setOrganizations(Array.isArray(organizationResult?.items) ? organizationResult.items : []); setEvents(Array.isArray(eventResult?.items) ? eventResult.items : []); }).catch(() => undefined); }, []);
  function update(name: string, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  function selectOrganization(id: string) { const organization = organizations.find((item) => item.id === id); setForm((current) => ({ ...current, organization_id: id, organization_name: organization?.name || (id ? current.organization_name : "") })); }
  function selectEvent(id: string) { const selected = events.find((item) => item.id === id); setForm((current) => ({ ...current, event_id: id, event_title: selected?.title || (id ? current.event_title : ""), event_date: selected?.date || (id ? current.event_date : ""), event_location: selected?.location || (id ? current.event_location : ""), event_url: selected?.id ? `${window.location.origin}/events/${selected.id}` : (id ? current.event_url : "") })); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!flyer) { setMessage("Please upload the event flyer with the SDTV media-partner logo included."); return; } if (!captchaToken) { setMessage("Please complete the human verification."); return; }
    setSaving(true); setMessage("Submitting your request…"); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); body.append("flyer", flyer); body.append("captcha_token", captchaToken);
    try { const response = await fetch("/api/media-partnership-request", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result?.error || "Could not submit request."); setMessage(`Thank you. ${site.name} received your media partnership request. Our team will review the event and contact you; submission does not guarantee coverage.`); setForm(blank); setFlyer(null); const input = document.getElementById("media-partner-flyer") as HTMLInputElement | null; if (input) input.value = ""; setCaptchaToken(""); if (window.turnstile && widgetId.current) window.turnstile.reset(widgetId.current); }
    catch (error: any) { setMessage(error?.message || "Could not submit request."); } finally { setSaving(false); }
  }
  const inputClass = "mt-1 w-full rounded-xl border border-slate-300 p-3 font-normal";
  return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader /><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" async defer onLoad={renderTurnstile} />
    <section className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="font-black uppercase tracking-[.2em] text-pink-300">Event collaboration</p><h1 className="mt-3 max-w-4xl text-4xl font-black md:text-6xl">Invite {site.name} to be your media partner</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">For eligible nonprofit and community events, SDTV can help amplify your event before it happens and may provide additional radio or on-site coverage when our volunteer team is available.</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-6 py-12 lg:grid-cols-[.9fr_1.1fr]">
      <div className="space-y-5"><article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">What media partnership may include</h2><ul className="mt-5 space-y-3 text-slate-700"><li>✓ Your approved event flyer published on SDTV Instagram up to two times before the event.</li><li>✓ Best-effort consideration for a radio interview before the event.</li><li>✓ Best-effort consideration for a follow-up radio conversation after the event.</li><li>✓ Best-effort consideration for an SDTV volunteer to attend and create a highlight video.</li></ul></article>
        <article className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><h2 className="text-xl font-black text-amber-950">Important expectations</h2><p className="mt-3 leading-7 text-amber-900">SDTV is a nonprofit, volunteer-supported organization. Radio interviews, attendance, filming, editing, posting dates, and highlight videos depend on editorial fit, volunteer availability, schedules, permissions, and technical capacity. We cannot guarantee any placement or coverage.</p></article>
        <article className="rounded-3xl border border-pink-200 bg-pink-50 p-7"><h2 className="text-xl font-black text-pink-950">Private ticketed events</h2><p className="mt-3 leading-7 text-pink-900">Private or commercial ticketed events may still request media partnership review. If you want SDTV to attend on the event day and produce a reel or highlight video, a production fee applies. SDTV will confirm scope and pricing before accepting paid coverage.</p></article>
        <article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-xl font-black">Before submitting</h2><p className="mt-3 text-slate-700">Add the official SDTV logo to the flyer and identify SDTV as a media partner. Upload that final flyer below. SDTV must review and accept the request before the partnership is considered confirmed.</p></article>
      </div>
      <form onSubmit={submit} className="h-fit rounded-3xl bg-white p-7 shadow-xl"><h2 className="text-3xl font-black">Media partnership request</h2><p className="mt-2 text-sm text-slate-600">Fields marked with * are required.</p><div className="mt-6 grid gap-4 md:grid-cols-2">
        <label className="font-bold md:col-span-2">Select an approved organization<select className={inputClass} value={form.organization_id} onChange={(e) => selectOrganization(e.target.value)}><option value="">Organization not listed / enter manually</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label>
        <label className="font-bold md:col-span-2">Organization name *<input required className={inputClass} value={form.organization_name} onChange={(e) => update("organization_name", e.target.value)} /></label>
        <label className="font-bold">Contact name *<input required className={inputClass} value={form.contact_name} onChange={(e) => update("contact_name", e.target.value)} /></label><label className="font-bold">Contact email *<input required type="email" className={inputClass} value={form.contact_email} onChange={(e) => update("contact_email", e.target.value)} /></label>
        <label className="font-bold">Contact phone<input className={inputClass} value={form.contact_phone} onChange={(e) => update("contact_phone", e.target.value)} /></label><label className="font-bold">Event type *<select required className={inputClass} value={form.event_type} onChange={(e) => update("event_type", e.target.value)}><option value="nonprofit_community">Nonprofit / community event</option><option value="private_ticketed">Private / ticketed event</option></select></label>
        <label className="font-bold md:col-span-2">Select an approved event<select className={inputClass} value={form.event_id} onChange={(e) => selectEvent(e.target.value)}><option value="">Event not listed / enter manually</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}{event.date ? ` — ${event.date}` : ""}</option>)}</select></label>
        <label className="font-bold md:col-span-2">Event title *<input required className={inputClass} value={form.event_title} onChange={(e) => update("event_title", e.target.value)} /></label><label className="font-bold">Event date *<input required type="date" className={inputClass} value={form.event_date} onChange={(e) => update("event_date", e.target.value)} /></label><label className="font-bold">Event location *<input required className={inputClass} value={form.event_location} onChange={(e) => update("event_location", e.target.value)} /></label>
        <label className="font-bold md:col-span-2">Event page or ticket URL<input type="url" className={inputClass} placeholder="https://…" value={form.event_url} onChange={(e) => update("event_url", e.target.value)} /></label>
        <label className="font-bold md:col-span-2">Final flyer with SDTV media-partner logo *<input id="media-partner-flyer" required type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className={inputClass} onChange={(e) => setFlyer(e.target.files?.[0] || null)} /><span className="mt-1 block text-xs font-normal text-slate-500">PDF, JPG, PNG, or WebP; maximum 10 MB.</span></label>
        <label className="font-bold md:col-span-2">Additional details<textarea className={`${inputClass} min-h-28`} value={form.notes} onChange={(e) => update("notes", e.target.value)} placeholder="Audience, nonprofit status, requested interview topics, event-day coverage needs…" /></label>
      </div><div className="mt-5 min-h-[90px] rounded-2xl border bg-slate-50 p-4">{siteKey ? <div ref={turnstileRef} /> : <p className="font-bold text-red-700">Turnstile is not configured.</p>}</div><p className="mt-4 text-xs leading-5 text-slate-500">By submitting, you confirm you are authorized to share the flyer and request use of the SDTV name/logo. This request is subject to SDTV review and does not guarantee publishing, interviews, attendance, filming, or production.</p><button disabled={saving || !siteKey} className="mt-5 w-full rounded-xl bg-pink-600 px-6 py-4 font-black text-white disabled:opacity-50">{saving ? "Submitting…" : "Submit Media Partnership Request"}</button>{message && <p className="mt-4 rounded-xl bg-amber-50 p-4 font-bold text-amber-900" role="status">{message}</p>}</form>
    </section><SiteFooter /></main>;
}
