"use client";

import Script from "next/script";
import { useEffect, useRef, useState, type FormEvent } from "react";
import SiteFooter from "../../components/SiteFooter";
import SiteHeader from "../../components/SiteHeader";
import { useCurrentSite } from "../../lib/sites/SiteContext";
import { getSupabaseBrowserClient } from "../../lib/supabaseBrowser";

declare global { interface Window { turnstile?: any } }
const supabase = getSupabaseBrowserClient();
const siteKey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY || process.env.NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY || "";
const blank = { organization_id: "", event_id: "", organization_name: "", organization_category: "", organization_location: "", organization_website: "", organization_description: "", contact_name: "", contact_email: "", contact_phone: "", event_title: "", event_date: "", event_location: "", event_url: "", event_type: "nonprofit_community", notes: "" };

export default function MediaPartnerRequestPage() {
  const site = useCurrentSite();
  const [form, setForm] = useState(blank); const [flyer, setFlyer] = useState<File | null>(null); const [organizationImage, setOrganizationImage] = useState<File | null>(null); const [mediaConsentAccepted, setMediaConsentAccepted] = useState(false); const [captchaToken, setCaptchaToken] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [organizations, setOrganizations] = useState<any[]>([]); const [events, setEvents] = useState<any[]>([]);
  const [socialReach, setSocialReach] = useState({ followers: 0, views: 0, platforms: 0 });
  const turnstileRef = useRef<HTMLDivElement | null>(null); const widgetId = useRef<string | null>(null);
  function renderTurnstile() { if (!siteKey || !turnstileRef.current || !window.turnstile || widgetId.current) return; widgetId.current = window.turnstile.render(turnstileRef.current, { sitekey: siteKey, callback: (token: string) => setCaptchaToken(token), "expired-callback": () => setCaptchaToken("") }); }
  useEffect(() => { const timer = window.setInterval(() => { renderTurnstile(); if (widgetId.current) window.clearInterval(timer); }, 300); return () => window.clearInterval(timer); }, []);
  useEffect(() => { void (async () => { try { const [organizationResult, eventResult] = await Promise.all([fetch("/api/mobile/v1/organizations?limit=100", { cache: "no-store" }).then((response) => response.json()), fetch("/api/mobile/v1/events?limit=100", { cache: "no-store" }).then((response) => response.json())]); const organizationItems = Array.isArray(organizationResult?.items) ? organizationResult.items : []; const eventItems = Array.isArray(eventResult?.items) ? eventResult.items : []; setOrganizations(organizationItems); setEvents(eventItems); const requestedEventId = new URLSearchParams(window.location.search).get("event") || ""; let selected = eventItems.find((item: any) => item.id === requestedEventId); if (requestedEventId && !selected) { const ownedResult = await supabase.from("events").select("id,title,date,location").eq("id", requestedEventId).eq("site_id", site.id).maybeSingle(); selected = ownedResult.data || null; } if (selected) { const linkResult = await supabase.from("event_organizations").select("organization_id,community_organizations(name)").eq("event_id", selected.id).eq("site_id", site.id).order("is_primary", { ascending: false }).limit(1).maybeSingle(); const linked: any = linkResult.data; setForm((current) => ({ ...current, organization_id: linked?.organization_id || "", organization_name: linked?.community_organizations?.name || "Independent event organizer", event_id: selected.id, event_title: selected.title || "", event_date: selected.date || "", event_location: selected.location || "", event_url: `${window.location.origin}/events/${selected.id}` })); } } catch { /* The form remains available for a new event. */ } })(); }, [site.id]);
  useEffect(() => { void supabase.from("social_media_stats").select("platform,followers,views").eq("site_id", site.id || "").then(({ data }) => { const rows = data || []; setSocialReach({ followers: rows.reduce((total: number, row: any) => total + Number(row.followers || 0), 0), views: rows.reduce((total: number, row: any) => total + Number(row.views || 0), 0), platforms: rows.length }); }); }, [site.id]);
  function update(name: string, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  function selectOrganization(id: string) { const organization = organizations.find((item) => item.id === id); setForm((current) => ({ ...current, organization_id: id, organization_name: organization?.name || (id ? current.organization_name : "") })); }
  function selectEvent(id: string) { const selected = events.find((item) => item.id === id); setForm((current) => ({ ...current, organization_name: id && !current.organization_name ? "Independent event organizer" : current.organization_name, event_id: id, event_title: selected?.title || (id ? current.event_title : ""), event_date: selected?.date || (id ? current.event_date : ""), event_location: selected?.location || (id ? current.event_location : ""), event_url: selected?.id ? `${window.location.origin}/events/${selected.id}` : (id ? current.event_url : "") })); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!flyer) { setMessage("Please upload the event flyer with the SDTV media-partner logo included."); return; } if (!captchaToken) { setMessage("Please complete the human verification."); return; }
    if (!mediaConsentAccepted) { setMessage("Please review and accept the Media Coverage & Consent terms."); return; }
    setSaving(true); setMessage("Submitting your request…"); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); body.append("flyer", flyer); if (organizationImage) body.append("organization_image", organizationImage); body.append("media_consent_accepted", "yes"); body.append("captcha_token", captchaToken);
    try { const session = await supabase.auth.getSession(); const token = session.data?.session?.access_token || ""; const response = await fetch("/api/media-partnership-request", { method: "POST", headers: token ? { Authorization: `Bearer ${token}` } : undefined, body }); const result = await response.json(); if (!response.ok) throw new Error(result?.error || "Could not submit request."); setMessage(`Thank you! ${site.name} received your request. We will review the partnership${form.organization_id && form.event_id ? " and proposed flyer update" : " and the new directory information"} before anything is published.`); setForm(blank); setFlyer(null); setOrganizationImage(null); setMediaConsentAccepted(false); const input = document.getElementById("media-partner-flyer") as HTMLInputElement | null; if (input) input.value = ""; const organizationInput = document.getElementById("media-partner-organization-image") as HTMLInputElement | null; if (organizationInput) organizationInput.value = ""; setCaptchaToken(""); if (window.turnstile && widgetId.current) window.turnstile.reset(widgetId.current); }
    catch (error: any) { setMessage(error?.message || "Could not submit request."); } finally { setSaving(false); }
  }
  const inputClass = "mt-1 w-full rounded-xl border border-slate-300 p-3 font-normal";
  return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader /><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" async defer onLoad={renderTurnstile} />
    <section className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="font-black uppercase tracking-[.2em] text-pink-300">Let’s share your event</p><h1 className="mt-3 max-w-4xl text-4xl font-black md:text-6xl">Invite {site.name} to be your media partner</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Tell us about your event and share the final flyer. Once the partnership is approved, we will help introduce it to the SDTV community.</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-6 py-12 lg:grid-cols-[.9fr_1.1fr]">
      <div className="space-y-5"><article className="overflow-hidden rounded-3xl bg-slate-950 p-7 text-white shadow-xl"><p className="text-sm font-black uppercase tracking-[.18em] text-pink-300">Why partner with SDTV?</p><h2 className="mt-2 text-3xl font-black">Help more people discover and remember your event</h2><p className="mt-4 leading-7 text-slate-300">Seattle Desi TV connects local events with a community audience already looking for cultural programs, nonprofit activities, organizers, businesses, and ways to participate.</p>{(socialReach.followers > 0 || socialReach.views > 0) && <div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black text-pink-300">{socialReach.followers.toLocaleString()}+</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-300">Social followers</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black text-pink-300">{socialReach.views.toLocaleString()}+</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-300">Recorded views</p></div></div>}<ul className="mt-6 space-y-3 text-sm leading-6 text-slate-200"><li>✓ Reach people beyond your organization’s existing audience.</li><li>✓ Build trust through association with a community-focused nonprofit media platform.</li><li>✓ Give your event additional visibility before the date and a longer life through post-event content.</li><li>✓ Make it easier for attendees to find the event page, location, registration details, and organizer information.</li></ul><p className="mt-5 text-xs leading-5 text-slate-400">Reach figures are drawn from the connected SDTV social accounts and may change as platforms update their reporting.</p></article><article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">What we’ll do after approval</h2><ul className="mt-5 space-y-3 text-slate-700"><li>✓ We guarantee at least one Instagram post using your approved, ready-to-publish event flyer.</li><li>✓ If you record the event and share a usable video with us, we will publish it on SDTV social channels.</li><li>✓ We will also consider a radio conversation before or after the event.</li><li>✓ When a volunteer is available, we may attend and help create event highlights.</li></ul></article>
        <article className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><h2 className="text-xl font-black text-amber-950">A quick note from our team</h2><p className="mt-3 leading-7 text-amber-900">SDTV is nonprofit and volunteer-supported. The Instagram post and organizer-provided video publication apply to approved partnerships and usable content that meets platform, permission, safety, and technical requirements. Interviews, attendance, filming, and SDTV-produced videos depend on volunteer availability and scheduling.</p></article>
        <article className="rounded-3xl border border-sky-200 bg-sky-50 p-7"><h2 className="text-xl font-black text-sky-950">When radio or in-person coverage is confirmed</h2><p className="mt-3 leading-7 text-sky-900">If the confirmed coverage requires SDTV volunteers to attend your event for an interview or to create a reel, we kindly ask the organizer to take care of admission or event tickets for the assigned volunteers.</p><p className="mt-3 leading-7 text-sky-900">We would also appreciate Seattle Desi TV being welcomed as an event media partner from the stage at least three times during the program. When recognizing your volunteers, a warm acknowledgement of the SDTV volunteers helping share your event with the community would mean a great deal to our team.</p></article>
        <article className="rounded-3xl border border-pink-200 bg-pink-50 p-7"><h2 className="text-xl font-black text-pink-950">Private ticketed events</h2><p className="mt-3 leading-7 text-pink-900">Private or commercial ticketed events may still request media partnership review. If you want SDTV to attend on the event day and produce a reel or highlight video, a production fee applies. SDTV will confirm scope and pricing before accepting paid coverage.</p></article>
        <article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-xl font-black">Before submitting</h2><p className="mt-3 text-slate-700">Add the official SDTV logo to the flyer and identify SDTV as a media partner. Upload that final flyer below. SDTV must review and accept the request before the partnership is considered confirmed.</p></article>
      </div>
      <form onSubmit={submit} className="h-fit rounded-3xl bg-white p-7 shadow-xl"><h2 className="text-3xl font-black">Media partnership request</h2><p className="mt-2 text-sm text-slate-600">Fields marked with * are required.</p><div className="mt-6 grid gap-4 md:grid-cols-2">
        <label className="font-bold md:col-span-2">Select an approved organization<select className={inputClass} value={form.organization_id} onChange={(e) => selectOrganization(e.target.value)}><option value="">Organization not listed / enter manually</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label>
        <label className="font-bold md:col-span-2">Organization name *<input required className={inputClass} value={form.organization_name} onChange={(e) => update("organization_name", e.target.value)} /></label>
        {!form.organization_id && !form.event_id && <div className="md:col-span-2 grid gap-4 rounded-2xl border border-pink-200 bg-pink-50 p-4 md:grid-cols-2"><p className="md:col-span-2 text-sm font-bold text-pink-950">Not listed? Add the organization here. It will be sent to SDTV for approval and then appear in the Organizations directory.</p><label className="font-bold">Organization category *<input required className={inputClass} placeholder="Nonprofit, arts, cultural…" value={form.organization_category} onChange={(e) => update("organization_category", e.target.value)} /></label><label className="font-bold">Organization location *<input required className={inputClass} placeholder="City, state" value={form.organization_location} onChange={(e) => update("organization_location", e.target.value)} /></label><label className="font-bold md:col-span-2">Organization website<input type="url" className={inputClass} placeholder="https://…" value={form.organization_website} onChange={(e) => update("organization_website", e.target.value)} /></label><label className="font-bold md:col-span-2">About the organization<textarea className={`${inputClass} min-h-24`} value={form.organization_description} onChange={(e) => update("organization_description", e.target.value)} /></label><label className="font-bold md:col-span-2">Organization logo or image *<input id="media-partner-organization-image" required type="file" accept="image/jpeg,image/png,image/webp" className={inputClass} onChange={(e) => setOrganizationImage(e.target.files?.[0] || null)} /><span className="mt-1 block text-xs font-normal text-slate-500">JPG, PNG, or WebP; used as the organization’s main directory image after approval.</span></label></div>}
        <label className="font-bold">Contact name *<input required className={inputClass} value={form.contact_name} onChange={(e) => update("contact_name", e.target.value)} /></label><label className="font-bold">Contact email *<input required type="email" className={inputClass} value={form.contact_email} onChange={(e) => update("contact_email", e.target.value)} /></label>
        <label className="font-bold">Contact phone<input className={inputClass} value={form.contact_phone} onChange={(e) => update("contact_phone", e.target.value)} /></label><label className="font-bold">Event type *<select required className={inputClass} value={form.event_type} onChange={(e) => update("event_type", e.target.value)}><option value="nonprofit_community">Nonprofit / community event</option><option value="private_ticketed">Private / ticketed event</option></select></label>
        <label className="font-bold md:col-span-2">Select an approved event<select className={inputClass} value={form.event_id} onChange={(e) => selectEvent(e.target.value)}><option value="">Event not listed / add it with this request</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}{event.date ? ` — ${event.date}` : ""}</option>)}</select><span className="mt-1 block text-xs font-normal text-slate-500">A new event is created as pending and appears publicly after SDTV approval.</span></label>
        <label className="font-bold md:col-span-2">Event title *<input required className={inputClass} value={form.event_title} onChange={(e) => update("event_title", e.target.value)} /></label><label className="font-bold">Event date *<input required type="date" className={inputClass} value={form.event_date} onChange={(e) => update("event_date", e.target.value)} /></label><label className="font-bold">Event location *<input required className={inputClass} value={form.event_location} onChange={(e) => update("event_location", e.target.value)} /></label>
        <label className="font-bold md:col-span-2">Event page or ticket URL<input type="url" className={inputClass} placeholder="https://…" value={form.event_url} onChange={(e) => update("event_url", e.target.value)} /></label>
        <label className="font-bold md:col-span-2">Final flyer with SDTV media-partner logo *<input id="media-partner-flyer" required type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className={inputClass} onChange={(e) => setFlyer(e.target.files?.[0] || null)} /><span className="mt-1 block text-xs font-normal text-slate-500">Maximum 10 MB. Use JPG, PNG, or WebP for a new event or to propose a replacement public flyer. A PDF is kept with the request but does not replace the event’s main image.</span></label>
        <label className="font-bold md:col-span-2">Additional details<textarea className={`${inputClass} min-h-28`} value={form.notes} onChange={(e) => update("notes", e.target.value)} placeholder="Audience, nonprofit status, requested interview topics, event-day coverage needs…" /></label>
      </div><section className="mt-6 rounded-2xl border border-slate-300 bg-slate-50 p-5"><h3 className="text-lg font-black">Media Coverage &amp; Consent</h3><div className="mt-3 space-y-3 text-sm leading-6 text-slate-700"><p>By inviting and/or engaging our organisation as a media partner for your event or activity, you acknowledge and grant permission to our authorised representatives to photograph, film, record, and otherwise document the event, including attendees, participants, speakers, performers, volunteers, staff, and other individuals present.</p><p>The resulting photographs, videos, audio recordings, and other media content may be used by our non-profit organisation for editorial, documentary, educational, archival, awareness, promotional, and social media purposes, including publication through our website, social media platforms, newsletters, reports, and other communication channels.</p><p>The event organiser/client is responsible for informing attendees and participants that media coverage will take place and, where applicable, obtaining any necessary permissions or consents from them.</p><p>By granting us media access, the organiser/client acknowledges and agrees to these terms, subject to applicable privacy and consent laws.</p></div><label className="mt-5 flex cursor-pointer items-start gap-3 rounded-xl border bg-white p-4 font-bold"><input required type="checkbox" checked={mediaConsentAccepted} onChange={(event) => setMediaConsentAccepted(event.target.checked)} className="mt-1 h-5 w-5 accent-pink-600" /><span>I have read, understand, and agree to the Media Coverage &amp; Consent terms above.</span></label></section><div className="mt-5 min-h-[90px] rounded-2xl border bg-slate-50 p-4">{siteKey ? <div ref={turnstileRef} /> : <p className="font-bold text-red-700">Turnstile is not configured.</p>}</div><p className="mt-4 text-xs leading-5 text-slate-500">By submitting, you confirm you are authorized to share these images, request use of the SDTV name/logo, and provide the organization and event information. Nothing is published until SDTV reviews it.</p><button disabled={saving || !siteKey || !mediaConsentAccepted} className="mt-5 w-full rounded-xl bg-pink-600 px-6 py-4 font-black text-white disabled:opacity-50">{saving ? "Submitting…" : "Submit Media Partnership Request"}</button>{message && <p className="mt-4 rounded-xl bg-amber-50 p-4 font-bold text-amber-900" role="status">{message}</p>}</form>
    </section><SiteFooter /></main>;
}
