import type { SupabaseClient } from "@supabase/supabase-js";
export type PublishingChannel = "website" | "newsletter" | "instagram" | "facebook" | "linkedin" | "pdf" | "email";
export type PublicationOutputRecord = { id: string; publication_id: string; campaign_id: string | null; output_type: string; channel: PublishingChannel; status: string; content: Record<string, unknown>; asset_url: string | null; published_url: string | null; scheduled_at: string | null; published_at: string | null; attempt_count: number; last_error: string | null; last_attempt_at: string | null; created_at: string; updated_at: string };
export type PublishAttemptRecord = { id: string; output_id: string | null; channel: PublishingChannel; action: string; status: string; error_message: string | null; attempted_at: string };
const OUTPUT_COLUMNS = "id,publication_id,campaign_id,output_type,channel,status,content,asset_url,published_url,scheduled_at,published_at,attempt_count,last_error,last_attempt_at,created_at,updated_at";
export async function listOutputs(supabase: SupabaseClient, publicationId: string): Promise<PublicationOutputRecord[]> { const { data, error } = await supabase.from("publication_outputs").select(OUTPUT_COLUMNS).eq("publication_id", publicationId).order("created_at", { ascending: false }); if (error) throw error; return (data || []) as unknown as PublicationOutputRecord[]; }
export async function listAttempts(supabase: SupabaseClient, publicationId: string): Promise<PublishAttemptRecord[]> { const { data, error } = await supabase.from("publication_publish_attempts").select("id,output_id,channel,action,status,error_message,attempted_at").eq("publication_id", publicationId).order("attempted_at", { ascending: false }).limit(100); if (error) throw error; return (data || []) as unknown as PublishAttemptRecord[]; }
export async function createCampaign(supabase: SupabaseClient, publicationId: string, name: string, channels: PublishingChannel[], userId: string, scheduledAt?: string | null) { const { data, error } = await supabase.from("publication_campaigns").insert({ publication_id: publicationId, name, campaign_type: "publication", status: scheduledAt ? "scheduled" : "draft", channels, scheduled_at: scheduledAt || null, created_by: userId }).select("id").single(); if (error) throw error; return String(data.id); }
export async function createOutputs(supabase: SupabaseClient, rows: Record<string, unknown>[]): Promise<PublicationOutputRecord[]> { const { data, error } = await supabase.from("publication_outputs").insert(rows).select(OUTPUT_COLUMNS); if (error) throw error; return (data || []) as unknown as PublicationOutputRecord[]; }
export async function updateOutput(supabase: SupabaseClient, outputId: string, changes: Record<string, unknown>): Promise<PublicationOutputRecord> { const { data, error } = await supabase.from("publication_outputs").update({ ...changes, updated_at: new Date().toISOString() }).eq("id", outputId).select(OUTPUT_COLUMNS).single(); if (error) throw error; return data as unknown as PublicationOutputRecord; }
export async function recordAttempt(supabase: SupabaseClient, row: Record<string, unknown>): Promise<void> { const { error } = await supabase.from("publication_publish_attempts").insert(row); if (error) throw error; }
