"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useParams } from "next/navigation";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

export default function QuickFormPublicPage() {
  const params = useParams(); const slug = String(Array.isArray(params?.slug) ? params.slug[0] : params?.slug || "");
  const [form, setForm] = useState<any>(null); const [answers, setAnswers] = useState<Record<string, any>>({}); const [message, setMessage] = useState("Loading form..."); const [saving, setSaving] = useState(false); const [done, setDone] = useState(false); const [website, setWebsite] = useState("");
  useEffect(() => { void fetch(`/api/forms/${encodeURIComponent(slug)}`, { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error || "Form not found."); setForm(result.form); setMessage(""); }).catch((error) => setMessage(error.message)); }, [slug]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage("Submitting..."); try { const response = await fetch(`/api/forms/${encodeURIComponent(slug)}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers, website }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Submission failed."); setDone(true); setMessage(result.message || "Thank you. Your response has been received."); } catch (error: any) { setMessage(error.message); } finally { setSaving(false); } }
  function control(field: any) { const common = { required: Boolean(field.required), value: answers[field.id] || "", onChange: (event: any) => setAnswers({ ...answers, [field.id]: event.target.value }), className: "mt-2 w-full rounded-xl border p-3 font-normal" }; if (field.type === "textarea") return <textarea {...common} className={`${common.className} min-h-32`} />; if (field.type === "select") return <select {...common}><option value="">Choose one</option>{field.options.map((option: string) => <option key={option}>{option}</option>)}</select>; if (field.type === "radio") return <div className="mt-2 grid gap-2">{field.options.map((option: string) => <label key={option} className="flex items-center gap-3 rounded-xl border p-3 font-normal"><input type="radio" name={field.id} value={option} checked={answers[field.id] === option} required={field.required} onChange={() => setAnswers({ ...answers, [field.id]: option })} />{option}</label>)}</div>; if (field.type === "checkbox") return <input type="checkbox" checked={Boolean(answers[field.id])} required={field.required} onChange={(event) => setAnswers({ ...answers, [field.id]: event.target.checked })} className="ml-3 h-5 w-5 accent-pink-600" />; return <input {...common} type={field.type === "phone" ? "tel" : field.type} />; }
  return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader/><section className="mx-auto max-w-3xl px-6 py-12"><div className="overflow-hidden rounded-3xl border bg-white shadow-xl"><div className="bg-slate-950 p-8 text-white"><p className="text-sm font-black uppercase tracking-[.2em] text-pink-300">Seattle Desi TV</p><h1 className="mt-3 text-4xl font-black">{form?.title || "Quick Form"}</h1>{form?.description && <p className="mt-4 whitespace-pre-line leading-7 text-slate-300">{form.description}</p>}</div><div className="p-6 md:p-8">{done ? <div className="rounded-2xl bg-emerald-50 p-6 text-lg font-bold text-emerald-900">{message}</div> : form?.status === "closed" ? <div className="rounded-2xl bg-amber-50 p-6 font-bold text-amber-900">This form is now closed.</div> : form ? <form onSubmit={submit} className="grid gap-5">{(form.fields || []).map((field: any) => <label key={field.id} className="block font-bold">{field.label}{field.required && <span className="text-pink-600"> *</span>}{control(field)}</label>)}<label className="hidden" aria-hidden="true">Website<input value={website} onChange={(event) => setWebsite(event.target.value)} tabIndex={-1}/></label><button disabled={saving} className="rounded-xl bg-pink-600 px-6 py-4 font-black text-white disabled:opacity-50">{saving ? "Submitting..." : "Submit"}</button>{message && <p className="rounded-xl bg-amber-50 p-4 font-bold text-amber-900" role="status">{message}</p>}</form> : <div className="rounded-xl bg-slate-100 p-5 font-bold">{message}</div>}</div></div></section><SiteFooter/></main>;
}
