"use client";
/* eslint-disable @next/next/no-img-element -- previews use runtime blob URLs and editor-controlled Cloudinary flyers */

import { useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PublicationRecord } from "../../../lib/publishing/types";
import { useWeeklyEventsInstagram } from "../../../hooks/useWeeklyEventsInstagram";
import { publishInstagramCarousel } from "../../../lib/publishing/services/instagramPublishingService";

export default function WeeklyEventsInstagramWorkspace({ supabase, publication }: { supabase: SupabaseClient; publication: PublicationRecord }) {
  const state = useWeeklyEventsInstagram(supabase, publication.id, publication.edition_label);
  const [approvedImageSignature, setApprovedImageSignature] = useState("");
  const [publishMessage, setPublishMessage] = useState("");
  const [publishing, setPublishing] = useState(false);
  const publishSignature = `${state.imageUrls.join("|")}::${state.caption}`;
  const approvedForPublishing = Boolean(state.imageUrls.length) && approvedImageSignature === publishSignature;
  async function publish() {
    if (!approvedForPublishing) return;
    setPublishing(true); setPublishMessage("");
    try { const result = await publishInstagramCarousel(supabase, state.imageUrls, state.caption); setPublishMessage(result.permalink ? `Published successfully: ${result.permalink}` : "Published successfully to Instagram."); setApprovedImageSignature(""); }
    catch (error) { setPublishMessage(error instanceof Error ? error.message : "Could not publish to Instagram."); }
    finally { setPublishing(false); }
  }
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,0.9fr)_minmax(420px,1.1fr)]">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-6">
      <p className="text-xs font-black uppercase tracking-[0.18em] text-pink-600">Weekly Events · Instagram</p><h2 className="mt-1 text-2xl font-black">Build a flyer carousel</h2><p className="mt-2 text-sm text-slate-600">Uses events already included in this publication. Exclude or edit an event in Edit items, then refresh here.</p>
      {state.loading ? <p className="mt-5 font-bold text-slate-500">Loading included events…</p> : !state.events.length ? <div className="mt-5 rounded-2xl bg-amber-50 p-4 font-bold text-amber-900">No included events are available. Add events in Discover content, then include them in Edit items.</div> : <div className="mt-5 grid gap-3">{state.events.map((event) => { const selected = state.selectedIds.includes(event.id); const position = state.selectedIds.indexOf(event.id); return <div key={event.id} className={`flex gap-3 rounded-2xl border p-3 ${selected ? "border-pink-300 bg-pink-50" : "border-slate-200"}`}><input aria-label={`Include ${event.title}`} type="checkbox" checked={selected} onChange={() => state.toggle(event.id)} className="mt-2 h-5 w-5 accent-pink-600" />{event.image_url ? <img src={event.image_url} alt="" className="h-20 w-16 rounded-xl object-cover" /> : <div className="grid h-20 w-16 place-items-center rounded-xl bg-slate-200 text-xs font-black">No flyer</div>}<div className="min-w-0 flex-1"><p className="font-black">{event.title || "Community Event"}</p><p className="mt-1 text-xs text-slate-500">{selected ? `Carousel position ${position + 2}` : "Not selected"}</p></div>{selected && <div className="grid content-center gap-1"><button type="button" onClick={() => state.move(event.id, -1)} disabled={position === 0} className="rounded-lg border bg-white px-2 py-1 font-black disabled:opacity-30">↑</button><button type="button" onClick={() => state.move(event.id, 1)} disabled={position === state.selectedIds.length - 1} className="rounded-lg border bg-white px-2 py-1 font-black disabled:opacity-30">↓</button></div>}</div>; })}</div>}
      <div className="mt-6 border-t pt-5"><h3 className="font-black">Editable post text</h3><div className="mt-3 grid gap-3"><label className="grid gap-1 text-sm font-bold">Cover headline<input value={state.copy.headline} onChange={(event) => state.updateCopy({ headline: event.target.value })} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-1 text-sm font-bold">Week / date label<input value={state.copy.weekLabel} onChange={(event) => state.updateCopy({ weekLabel: event.target.value })} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-1 text-sm font-bold">Cover introduction<textarea rows={3} value={state.copy.intro} onChange={(event) => state.updateCopy({ intro: event.target.value })} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-1 text-sm font-bold">Instagram caption<textarea rows={5} value={state.copy.caption} onChange={(event) => state.updateCopy({ caption: event.target.value })} className="rounded-xl border p-3 font-normal" /></label><label className="grid gap-1 text-sm font-bold">Hashtags<input value={state.copy.hashtags} onChange={(event) => state.updateCopy({ hashtags: event.target.value })} className="rounded-xl border p-3 font-normal" /></label></div></div>
      <button type="button" disabled={state.busy || !state.selectedEvents.length} onClick={() => void state.generate()} className="mt-5 w-full rounded-xl bg-slate-950 px-5 py-4 font-black text-white disabled:opacity-50">{state.busy ? "Working…" : `Generate cover + ${state.selectedEvents.length} flyer slides`}</button>{state.error && <div className="mt-3 rounded-xl bg-red-50 p-3 font-bold text-red-700">{state.error}</div>}{state.message && <div className="mt-3 rounded-xl bg-emerald-50 p-3 font-bold text-emerald-700">{state.message}</div>}
    </section>
    <aside className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><h2 className="text-2xl font-black">Carousel preview</h2><p className="mt-1 text-sm text-slate-500">Instagram portrait size · 1080 × 1350</p>{state.imageUrls.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{state.imageUrls.map((url, index) => <div key={`${url}-${index}`} className="overflow-hidden rounded-2xl border bg-slate-950"><p className="px-3 py-2 text-xs font-black text-white">Slide {index + 1} of {state.imageUrls.length}</p><img src={url} alt={`Weekly events carousel slide ${index + 1}`} className="aspect-[4/5] w-full object-contain" /><a href={url} download={`sdtv-weekly-events-slide-${index + 1}.png`} className="block bg-white px-3 py-2 text-center text-sm font-black text-pink-700">Download slide</a></div>)}</div> : <div className="mt-5 grid aspect-[4/3] place-items-center rounded-2xl bg-slate-100 p-8 text-center font-bold text-slate-400">Generate the carousel to preview every slide.</div>}
      <div className="mt-6 rounded-2xl bg-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-black">Final editable caption</p><p className="text-xs text-slate-500">This exact text will be published to Instagram.</p></div>{state.captionEdited && <button type="button" onClick={state.resetFinalCaption} className="rounded-lg border bg-white px-3 py-2 text-xs font-black">Reset generated caption</button>}</div><textarea value={state.caption} onChange={(event) => state.updateFinalCaption(event.target.value)} rows={12} maxLength={2200} className="mt-3 w-full rounded-xl border bg-white p-3 text-sm" /><div className="mt-2 flex items-center justify-between gap-2"><span className={`text-xs font-bold ${state.caption.length > 2200 ? "text-red-600" : "text-slate-500"}`}>{state.caption.length} / 2,200 characters</span><button type="button" onClick={() => void navigator.clipboard.writeText(state.caption)} className="rounded-xl border bg-white px-4 py-2 text-sm font-black">Copy caption</button></div></div>
      <button type="button" disabled={state.busy || !state.files.length} onClick={() => void state.upload()} className="mt-5 w-full rounded-xl bg-pink-600 px-5 py-4 font-black text-white disabled:opacity-50">Upload reviewed slides</button>
      {state.imageUrls.length > 0 && state.imageUrls.every((url) => url.startsWith("https://")) && <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4"><p className="font-black text-red-950">Final Instagram approval</p><p className="mt-1 text-sm text-red-900">Review every uploaded slide and the complete caption. Approval resets automatically if either changes.</p>{!approvedForPublishing ? <button type="button" disabled={!state.caption.trim() || state.caption.length > 2200} onClick={() => setApprovedImageSignature(publishSignature)} className="mt-4 w-full rounded-xl border-2 border-emerald-700 bg-white px-5 py-4 font-black text-emerald-800 disabled:opacity-40">Everything looks good</button> : <div className="mt-4 rounded-xl bg-emerald-100 p-3 text-center font-black text-emerald-900">✓ Images and caption approved</div>}<button type="button" disabled={!approvedForPublishing || publishing} onClick={() => void publish()} className="mt-3 w-full rounded-xl bg-red-700 px-5 py-4 font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{publishing ? "Publishing to Instagram…" : "Publish carousel to Instagram"}</button></div>}
      {publishMessage && <div className="mt-3 rounded-xl bg-amber-50 p-3 font-bold text-amber-900">{publishMessage}</div>}
    </aside>
  </div>;
}
