-- Constraints captured from production.
-- STATUS: Captured, but not yet fully converted into final restore-safe SQL.
--
-- The production constraints export has 80 constraints across 36 tables.
-- A copy has already been captured at:
-- supabase/exports/constraints.json
--
-- This file will be converted into ALTER TABLE ... ADD CONSTRAINT statements
-- after tables.sql contains all 36 production table definitions.
--
-- Do not run this file yet.
