-- Indexes captured from production.
-- CREATE INDEX IF NOT EXISTS is used for idempotency.

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_key ON public.admins USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS admins_pkey ON public.admins USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS community_groups_pkey ON public.community_groups USING btree (id);
CREATE INDEX IF NOT EXISTS community_groups_status_created_idx ON public.community_groups USING btree (status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS community_organizations_pkey ON public.community_organizations USING btree (id);
CREATE INDEX IF NOT EXISTS community_orgs_status_created_idx ON public.community_organizations USING btree (status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS contact_requests_pkey ON public.contact_requests USING btree (id);
CREATE INDEX IF NOT EXISTS idx_contact_requests_created ON public.contact_requests USING btree (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS crew_availability_pkey ON public.crew_availability USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS crew_availability_user_id_available_date_key ON public.crew_availability USING btree (user_id, available_date);
CREATE INDEX IF NOT EXISTS event_coverage_sources_event_id_idx ON public.event_coverage_sources USING btree (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_coverage_sources_pkey ON public.event_coverage_sources USING btree (id);
CREATE INDEX IF NOT EXISTS event_coverage_sources_status_idx ON public.event_coverage_sources USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS event_crew_assignments_event_id_user_id_key ON public.event_crew_assignments USING btree (event_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_crew_assignments_pkey ON public.event_crew_assignments USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS event_crew_media_submissions_assignment_unique ON public.event_crew_media_submissions USING btree (assignment_id) WHERE (assignment_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS event_crew_media_submissions_event_id_idx ON public.event_crew_media_submissions USING btree (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_crew_media_submissions_pkey ON public.event_crew_media_submissions USING btree (id);
CREATE INDEX IF NOT EXISTS event_deliverables_completed_idx ON public.event_deliverables USING btree (event_id, completed);
CREATE INDEX IF NOT EXISTS event_deliverables_event_id_idx ON public.event_deliverables USING btree (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_deliverables_event_type_unique ON public.event_deliverables USING btree (event_id, deliverable_type);
CREATE UNIQUE INDEX IF NOT EXISTS event_deliverables_pkey ON public.event_deliverables USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS event_influencer_intents_event_id_user_email_key ON public.event_influencer_intents USING btree (event_id, user_email);
CREATE UNIQUE INDEX IF NOT EXISTS event_influencer_intents_pkey ON public.event_influencer_intents USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS event_video_notifications_pkey ON public.event_video_notifications USING btree (id);
CREATE INDEX IF NOT EXISTS event_video_notifications_recipient_idx ON public.event_video_notifications USING btree (recipient_user_id, is_read);
CREATE UNIQUE INDEX IF NOT EXISTS event_video_revisions_pkey ON public.event_video_revisions USING btree (id);
CREATE INDEX IF NOT EXISTS event_video_revisions_workflow_idx ON public.event_video_revisions USING btree (workflow_id, revision_number DESC);
CREATE INDEX IF NOT EXISTS event_video_workflows_crew_idx ON public.event_video_workflows USING btree (lower(crew_reviewer_email));
CREATE INDEX IF NOT EXISTS event_video_workflows_editor_idx ON public.event_video_workflows USING btree (lower(assigned_editor_email));
CREATE INDEX IF NOT EXISTS event_video_workflows_event_id_idx ON public.event_video_workflows USING btree (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_video_workflows_event_unique ON public.event_video_workflows USING btree (event_id);
CREATE UNIQUE INDEX IF NOT EXISTS event_video_workflows_pkey ON public.event_video_workflows USING btree (id);
CREATE INDEX IF NOT EXISTS event_video_workflows_status_idx ON public.event_video_workflows USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS events_pkey ON public.events USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS featured_social_content_pkey ON public.featured_social_content USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS festival_hero_assets_pkey ON public.festival_hero_assets USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS hero_analytics_pkey ON public.hero_analytics USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS homepage_hero_banners_pkey ON public.homepage_hero_banners USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS homepage_settings_pkey ON public.homepage_settings USING btree (section_key);
CREATE UNIQUE INDEX IF NOT EXISTS homepage_sponsors_pkey ON public.homepage_sponsors USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS homepage_testimonials_pkey ON public.homepage_testimonials USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS influencer_profiles_email_key ON public.influencer_profiles USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS influencer_profiles_pkey ON public.influencer_profiles USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS local_businesses_pkey ON public.local_businesses USING btree (id);
CREATE INDEX IF NOT EXISTS newsletter_campaigns_created_at_idx ON public.newsletter_campaigns USING btree (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_campaigns_pkey ON public.newsletter_campaigns USING btree (id);
CREATE INDEX IF NOT EXISTS newsletter_campaigns_status_idx ON public.newsletter_campaigns USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_settings_pkey ON public.newsletter_settings USING btree (section_key);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_subscribers_email_key ON public.newsletter_subscribers USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_subscribers_pkey ON public.newsletter_subscribers USING btree (id);
CREATE INDEX IF NOT EXISTS newsletter_subscribers_status_idx ON public.newsletter_subscribers USING btree (status);
CREATE INDEX IF NOT EXISTS newsletter_subscribers_subscribed_at_idx ON public.newsletter_subscribers USING btree (subscribed_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS notifications_pkey ON public.notifications USING btree (id);
CREATE INDEX IF NOT EXISTS public_content_requests_created_at_idx ON public.public_content_requests USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS public_content_requests_editor_idx ON public.public_content_requests USING btree (assigned_editor_email);
CREATE UNIQUE INDEX IF NOT EXISTS public_content_requests_pkey ON public.public_content_requests USING btree (id);
CREATE INDEX IF NOT EXISTS public_content_requests_status_idx ON public.public_content_requests USING btree (status);
CREATE INDEX IF NOT EXISTS public_content_requests_submitter_idx ON public.public_content_requests USING btree (submitter_user_id);
CREATE INDEX IF NOT EXISTS public_visibility_controls_disabled_idx ON public.public_visibility_controls USING btree (public_visibility_disabled);
CREATE UNIQUE INDEX IF NOT EXISTS public_visibility_controls_pkey ON public.public_visibility_controls USING btree (email);
CREATE INDEX IF NOT EXISTS public_visibility_controls_user_id_idx ON public.public_visibility_controls USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS radio_team_members_pkey ON public.radio_team_members USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS radio_team_members_user_id_unique ON public.radio_team_members USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS social_media_stats_pkey ON public.social_media_stats USING btree (platform);
CREATE UNIQUE INDEX IF NOT EXISTS sponsors_pkey ON public.sponsors USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS team_members_pkey ON public.team_members USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS team_members_user_id_unique ON public.team_members USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS user_profiles_email_idx ON public.user_profiles USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_email_key ON public.user_profiles USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_pkey ON public.user_profiles USING btree (user_id);
CREATE INDEX IF NOT EXISTS user_profiles_role_idx ON public.user_profiles USING btree (role);
CREATE INDEX IF NOT EXISTS user_profiles_visibility_idx ON public.user_profiles USING btree (public_visibility_disabled);
CREATE UNIQUE INDEX IF NOT EXISTS user_role_requests_pkey ON public.user_role_requests USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS volunteer_onboarding_submissions_pkey ON public.volunteer_onboarding_submissions USING btree (id);