import type { DailyAdminDigest, DigestRoleRequest, DigestSubmission, DigestUser } from "../../lib/adminDigest/types";

const when = (value: string) => new Date(value).toLocaleString();
const status = (value: string) => value.replaceAll("_", " ");

function Section({ title, count, href, children }: { title: string; count: number; href?: string; children: React.ReactNode }) {
  return <section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between gap-4 border-b bg-slate-50 px-5 py-4"><div><h3 className="text-xl font-black">{title}</h3>{href && <a href={href} className="text-sm font-black text-pink-600">Open in Studio →</a>}</div><span className="rounded-full bg-slate-950 px-3 py-1 text-sm font-black text-white">{count}</span></div><div>{children}</div></section>;
}
function Empty() { return <p className="p-5 text-sm text-slate-500">No records added in this date range.</p>; }
function Users({ rows }: { rows: DigestUser[] }) { return rows.length ? <div className="divide-y">{rows.map((row) => <div key={row.id} className="grid gap-1 p-5 md:grid-cols-[1fr_1fr_auto]"><b>{row.name || "Name not provided"}</b><span>{row.email}</span><span className="text-sm text-slate-500">{when(row.createdAt)}</span></div>)}</div> : <Empty />; }
function Requests({ rows }: { rows: DigestRoleRequest[] }) { return rows.length ? <div className="divide-y">{rows.map((row) => <div key={row.id} className="grid gap-1 p-5 md:grid-cols-[1fr_auto_auto]"><b>{row.email}</b><span className="capitalize">{status(row.status)}</span><span className="text-sm text-slate-500">{when(row.createdAt)}</span></div>)}</div> : <Empty />; }
function Submissions({ rows, error }: { rows: DigestSubmission[]; error: string | null }) { if (error) return <p className="p-5 text-sm font-bold text-red-700">This module could not be queried. Check its database setup.</p>; return rows.length ? <div className="divide-y">{rows.map((row) => <div key={row.id} className="grid gap-1 p-5 md:grid-cols-[1fr_auto_auto]"><b>{row.title}</b><span className="capitalize">{status(row.status)}</span><span className="text-sm text-slate-500">{when(row.createdAt)}</span></div>)}</div> : <Empty />; }

export default function ActivityReport({ report }: { report: DailyAdminDigest }) {
  const total = report.users.length + report.volunteerRequests.length + report.teamMemberRequests.length + report.submissions.reduce((sum, section) => sum + section.items.length, 0);
  return <div className="mt-6"><div className="mb-5 rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm font-black uppercase text-pink-300">Live database results</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-black">Platform Activity Report</h2><p className="mt-1 text-slate-300">{when(report.from)} through {when(report.to)}</p></div><p className="text-4xl font-black">{total} <span className="text-base text-slate-300">total</span></p></div></div><div className="grid gap-5"><Section title="New registrations" count={report.users.length} href="/studio/users"><Users rows={report.users} /></Section><Section title="Volunteer requests" count={report.volunteerRequests.length} href="/studio/volunteers"><Requests rows={report.volunteerRequests} /></Section><Section title="Team-member requests" count={report.teamMemberRequests.length} href="/studio/roles"><Requests rows={report.teamMemberRequests} /></Section>{report.submissions.map((section) => <Section key={section.key} title={section.label} count={section.items.length} href={section.studioPath}><Submissions rows={section.items} error={section.error} /></Section>)}</div></div>;
}
