/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "../../../components/SiteHeader";
import SiteFooter from "../../../components/SiteFooter";
import { resolveCurrentSite } from "../../../lib/sites/siteResolver";
import { getPublishedCommunityStory } from "../../../lib/communityStories/server";

async function story(slug: string) { const site = await resolveCurrentSite(); return getPublishedCommunityStory(site.id, slug); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const row: any = await story(slug); if (!row) return { title: "Story not found", robots: { index: false } }; return { title: row.title, description: row.summary, alternates: { canonical: `/news/stories/${row.slug}` }, openGraph: { title: row.title, description: row.summary, type: "article", images: row.image_urls?.[0] ? [row.image_urls[0]] : [] } }; }
export default async function StoryPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const row: any = await story(slug); if (!row) notFound(); return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader /><article><header className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto max-w-4xl"><Link href="/news" className="font-black text-pink-300">← Newsroom</Link><p className="mt-8 text-sm font-black uppercase tracking-widest text-pink-300">{row.category || "Community Story"}</p><h1 className="mt-3 text-4xl font-black leading-tight md:text-6xl">{row.title}</h1><p className="mt-5 text-lg text-slate-300">{row.author_name ? `By ${row.author_name}` : "Seattle Desi TV"}{row.location ? ` · ${row.location}` : ""}</p></div></header><div className="mx-auto max-w-4xl px-6 py-12">{row.image_urls?.map((url: string, index: number) => <img key={url} src={url} alt={index === 0 ? row.title : ""} className="mb-8 w-full rounded-3xl object-cover" />)}<p className="text-xl font-semibold leading-8 text-slate-700">{row.summary}</p><div className="mt-8 whitespace-pre-line text-lg leading-8 text-slate-700">{row.body}</div>{row.video_url && <a href={row.video_url} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-xl bg-pink-600 px-5 py-3 font-black text-white">Watch video ↗</a>}{row.source_url && <p className="mt-8 border-t pt-6"><a href={row.source_url} target="_blank" rel="noreferrer" className="font-bold text-pink-600">Original source ↗</a></p>}</div></article><SiteFooter /></main>; }
