create table if not exists public.engagement_events (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('business','organization','event','group','contributor','video','radio','newsletter','page')),
  entity_id text,
  entity_name text,
  action_type text not null,
  page_path text,
  target_url text,
  session_id text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists engagement_events_created_idx on public.engagement_events(created_at desc);
create index if not exists engagement_events_entity_idx on public.engagement_events(entity_type, entity_id, created_at desc);
create index if not exists engagement_events_action_idx on public.engagement_events(action_type, created_at desc);

alter table public.engagement_events enable row level security;

drop policy if exists "engagement events public insert" on public.engagement_events;
create policy "engagement events public insert"
on public.engagement_events for insert
to anon, authenticated
with check (true);

drop policy if exists "engagement events admins read" on public.engagement_events;
create policy "engagement events admins read"
on public.engagement_events for select
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
       or lower(a.email) = lower(coalesce(auth.jwt() ->> 'email',''))
  )
);

comment on table public.engagement_events is 'Lightweight, non-blocking engagement events for SDTV listings and content.';