"use client";
/* eslint-disable @next/next/no-img-element -- Studio previews user-uploaded public media */
import { useMemo, useState } from "react";
import StudioHeader from "../../components/StudioHeader";
import PressReleaseForm from "../../components/pressReleases/PressReleaseForm";
import { usePressReleases } from "../../hooks/usePressReleases";

export default function StudioPressReleasesPage() {
  const data = usePressReleases("admin");
  const [filter, setFilter] = useState("open");
  const [notes, setNotes] = useState<Record<string, string>>({});
  const visible = useMemo(() => data.releases.filter((release) => filter === "all" || (filter === "open" ? ["pending", "changes_requested"].includes(release.status) : release.status === filter)), [data.releases, filter]);
  return <main className="min-h-screen bg-slate-100 text-slate-950"><StudioHeader/><section className="mx-auto max-w-7xl px-6 py-10"><p className="font-black uppercase tracking-wide text-pink-600">Community newsroom</p><h1 className="mt-2 text-4xl font-black">Press Releases</h1><p className="mt-2 max-w-3xl text-slate-600">Create official SDTV releases or review community submissions before they appear publicly.</p>
    <div className="mt-8"><PressReleaseForm admin saving={data.saving} error={data.error} onCreate={data.create} onUpload={data.upload}/></div>
    <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Moderation Queue</h2><p className="text-sm text-slate-500">{visible.length} release{visible.length === 1 ? "" : "s"} in this view</p></div><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl border p-3 font-bold"><option value="open">Open review</option><option value="all">All</option><option value="pending">Pending</option><option value="changes_requested">Changes requested</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="archived">Archived</option></select></div>
      <div className="mt-6 grid gap-5">{visible.map((release) => <article key={release.id} className="rounded-2xl border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-pink-600">{release.status.replaceAll("_", " ")} · {release.release_date}</p><h3 className="mt-1 text-2xl font-black">{release.title}</h3><p className="mt-1 font-bold text-slate-500">{release.organization_name || "Community submission"}</p></div>{release.image_urls[0] && <img src={release.image_urls[0]} alt="" className="h-24 w-36 rounded-xl object-cover"/>}</div><p className="mt-4 text-slate-600">{release.summary}</p><details className="mt-3 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer font-black">Read full text</summary><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-700">{release.body}</p></details>{release.documents?.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{release.documents.map((document) => <a key={document.url} href={document.url} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-sm font-black text-pink-600">{document.name}</a>)}</div>}<input value={notes[release.id] ?? release.admin_notes ?? ""} onChange={(e) => setNotes((current) => ({ ...current, [release.id]: e.target.value }))} placeholder="Review notes for submitter" className="mt-4 w-full rounded-xl border p-3"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={data.saving} onClick={() => void data.review(release.id, "approve", notes[release.id] || "")} className="rounded-xl bg-emerald-700 px-4 py-2 font-black text-white">Approve & Publish</button><button disabled={data.saving} onClick={() => void data.review(release.id, "changes", notes[release.id] || "")} className="rounded-xl bg-amber-400 px-4 py-2 font-black">Request Changes</button><button disabled={data.saving} onClick={() => void data.review(release.id, "reject", notes[release.id] || "")} className="rounded-xl bg-red-700 px-4 py-2 font-black text-white">Reject</button>{release.status === "approved" && <button disabled={data.saving} onClick={() => void data.review(release.id, "archive", notes[release.id] || "")} className="rounded-xl bg-slate-700 px-4 py-2 font-black text-white">Archive</button>}</div></article>)}{!data.loading && !visible.length && <p className="rounded-2xl border border-dashed p-8 text-center text-slate-500">No press releases in this view.</p>}</div>
    </section></section></main>;
}
