"use client";

import { useEffect, useState } from "react";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import { getSupabaseBrowserClient } from "../../lib/supabaseBrowser";

const supabase = getSupabaseBrowserClient();

export default function SuggestBusinessEditPage() {
  const [business, setBusiness] = useState<any>(null), [user, setUser] = useState<any>(null), [message, setMessage] = useState("Loading business...");
  const [form, setForm] = useState({ name: "", email: "", suggestion: "" }), [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { const id = new URLSearchParams(window.location.search).get("business"); const auth = await supabase.auth.getUser(); const currentUser = auth.data.user || null; setUser(currentUser); if (currentUser) setForm((v) => ({ ...v, name: currentUser.user_metadata?.full_name || currentUser.user_metadata?.name || "", email: currentUser.email || "" })); if (!id) return setMessage("Business not specified."); const result = await supabase.from("local_businesses").select("id,name,address").eq("id", id).eq("status", "approved").maybeSingle(); if (result.error || !result.data) return setMessage("Business not found."); setBusiness(result.data); setMessage(""); })(); }, []);
  async function submit() { if (!form.suggestion.trim()) return setMessage("Please describe the correction or improvement."); setSaving(true); const { error } = await supabase.from("business_edit_suggestions").insert({ business_id: business.id, submitter_user_id: user?.id || null, submitter_name: form.name.trim() || null, submitter_email: form.email.trim().toLowerCase() || null, suggestion: form.suggestion.trim() }); setSaving(false); if (error) return setMessage(error.message); setForm((v)=>({...v,suggestion:""})); setMessage("Thank you. Your suggestion was sent to SDTV for review."); }
  return <main className="min-h-screen bg-slate-50 text-slate-950"><SiteHeader/><section className="mx-auto max-w-3xl px-6 py-12"><p className="font-black uppercase tracking-wide text-pink-600">Community Correction</p><h1 className="mt-2 text-4xl font-black">Suggest an edit</h1>{business&&<div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">{business.name}</h2><p className="mt-1 text-slate-500">{business.address}</p></div>}<div className="mt-6 rounded-3xl border bg-white p-6 shadow-sm">{message&&<div className="mb-5 rounded-xl bg-amber-50 p-4 font-bold text-amber-900">{message}</div>}{business&&<div className="grid gap-4"><label className="font-bold">Your name (optional)<input className="mt-1 w-full rounded-xl border p-3" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label className="font-bold">Email (optional)<input type="email" className="mt-1 w-full rounded-xl border p-3" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label className="font-bold">What should be corrected?<textarea className="mt-1 min-h-36 w-full rounded-xl border p-3" placeholder="Include the current information, the corrected information, and a source when possible." value={form.suggestion} onChange={(e)=>setForm({...form,suggestion:e.target.value})}/></label><button disabled={saving} onClick={submit} className="rounded-xl bg-pink-600 px-5 py-3 font-black text-white disabled:opacity-50">{saving?"Submitting...":"Send suggestion"}</button></div>}</div></section><SiteFooter/></main>;
}
